/*
 * XenForo album_sortable.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
/*
 TinySort 1.5.6
 Copyright (c) 2008-2013 Ron Valstar http://tinysort.sjeiti.com/
 License:
     MIT: http://www.opensource.org/licenses/mit-license.php
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,c){a instanceof String&&(a=String(a));for(var f=a.length,b=0;b<f;b++){var x=a[b];if(e.call(c,x,b,a))return{i:b,v:x}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,e,c,f){if(e){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var b=a[f];b in c||(c[b]={});c=c[b]}a=a[a.length-1];f=c[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
!function(a,e,c,f){XenForo.XenGallerySortable=function(a){this.__construct(a)};XenForo.XenGallerySortable.prototype={__construct:function(b){this.container=b;b.sortable({forcePlaceholderSize:!0}).bind({sortupdate:function(a){},dragstart:function(a){console.log("drag start, %o",a.target)},dragend:function(b){console.log("drag end");a(".Sort").removeClass("desc asc selected")}});a(".Sort").bind({click:a.context(this,"sortListPrep")})},sortListPrep:function(b){b.preventDefault();$target=this.container.data("sort-target");
$sort=a(b.target);$direction=$sort.data("sort-direction");a(".Sort").each(function(b){a(this).data("sort-direction","asc");a(this).removeClass("desc asc selected")});"desc"==$direction?($altDirection="asc",$sort.data("sort-direction",$altDirection),$sort.removeClass($altDirection),$sort.addClass($direction+" selected")):"asc"==$direction&&($altDirection="desc",$sort.data("sort-direction",$altDirection),$sort.removeClass($altDirection),$sort.addClass($direction),$sort.addClass($direction+" selected"));
a($target).tsort({data:$sort.data("sort-type"),order:$direction})}};XenForo.register(".Sortable","XenForo.XenGallerySortable")}(jQuery,this,document);
(function(a,e){function c(a,q){for(var b=0,c=a.length;b<c;b++)if(a[b]==q)return!0;return!1}var f=parseFloat,b=Math.min,x=/(-?\d+\.?\d*)$/g,I=/(\d+\.?\d*)$/g,B=[],C=[],u=function(a,q){for(var b=a.length,c=b,e;c--;)e=b-c-1,q(a[e],e)},E=Array.prototype.indexOf||function(a,b){var c=this.length;b=Number(b)||0;b=0>b?Math.ceil(b):Math.floor(b);for(0>b&&(b+=c);b<c;b++)if(b in this&&this[b]===a)return b;return-1};a.tinysort={id:"TinySort",version:"1.5.6",copyright:"Copyright (c) 2008-2013 Ron Valstar",uri:"http://tinysort.sjeiti.com/",
licensed:{MIT:"http://www.opensource.org/licenses/mit-license.php"},plugin:function(){var a=function(a,b){B.push(a);C.push(b)};a.indexOf=E;return a}(),defaults:{order:"asc",attr:null,data:null,useVal:!1,place:"start",returns:!1,cases:!1,forceStrings:!1,ignoreDashes:!1,sortFunction:null}};a.fn.extend({tinysort:function(){var y,q,A=[],v=[],D=[],z=[],t=0,l=[],m=[],K=function(a){u(B,function(b){b.call(b,a)})},F=function(a,b){"string"==typeof b&&(a.cases||(b=(a=b)&&a.toLowerCase?a.toLowerCase():a),b=b.replace(/^\s*(.*?)\s*$/i,
"$1"));return b},L=function(a,b){var c=0;for(0!==t&&(t=0);0===c&&t<w;){var e=z[t],g=e.oSettings,d=g.ignoreDashes?I:x;K(g);if(g.sortFunction)c=g.sortFunction(a,b);else if("rand"==g.order)c=.5>Math.random()?1:-1;else{var h=!1,k=F(g,a.s[t]),n=F(g,b.s[t]);if(!g.forceStrings&&(g="string"==typeof k?k&&k.match(d):!1,d="string"==typeof n?n&&n.match(d):!1,g&&d)){var J=k.substr(0,k.length-g[0].length),l=n.substr(0,n.length-d[0].length);J==l&&(h=!0,k=f(g[0]),n=f(d[0]))}c=e.iAsc*(k<n?-1:k>n?1:0)}u(C,function(a){c=
a.call(a,h,k,n,c)});0===c&&t++}return c};var d=0;for(q=arguments.length;d<q;d++){var p=arguments[d];"string"==typeof p?l.push(p)-1>m.length&&(m.length=l.length-1):m.push(p)>l.length&&(l.length=m.length)}l.length>m.length&&(m.length=l.length);var w=l.length;0===w&&(w=l.length=1,m.push({}));d=0;for(q=w;d<q;d++){p=l[d];var r=a.extend({},a.tinysort.defaults,m[d]),G=!(!p||""===p),H=G&&":"===p[0];z.push({sFind:p,oSettings:r,bFind:G,bAttr:!(null===r.attr||""===r.attr),bData:null!==r.data,bFilter:H,$Filter:H?
this.filter(p):this,fnSort:r.sortFunction,iAsc:"asc"==r.order?1:-1})}this.each(function(b,c){var d=a(c),n=d.parent().get(0),g,f=[];for(y=0;y<w;y++){var h=z[y],k=h.bFind?h.bFilter?h.$Filter.filter(c):d.find(h.sFind):d;f.push(h.bData?k.data(h.oSettings.data):h.bAttr?k.attr(h.oSettings.attr):h.oSettings.useVal?k.val():k.text());g===e&&(g=k)}c=E.call(D,n);0>c&&(c=D.push(n)-1,v[c]={s:[],n:[]});0<g.length?v[c].s.push({s:f,e:d,n:b}):v[c].n.push({e:d,n:b})});u(v,function(a){a.s.sort(L)});u(v,function(a){var e=
a.s;a=a.n;var f=e.length,l=a.length,g=f+l,p=[],h=g,k=[0,0];switch(r.place){case "first":u(e,function(a){h=b(h,a.n)});break;case "org":u(e,function(a){p.push(a.n)});break;case "end":h=l;break;default:h=0}for(d=0;d<g;d++){var q=(l=c(p,d)?!0:d>=h&&d<h+f)?0:1,m=(l?e:a)[k[q]].e;m.parent().append(m);!l&&r.returns||A.push(m.get(0));k[q]++}});this.length=0;Array.prototype.push.apply(this,A);return this}});a.fn.TinySort=a.fn.Tinysort=a.fn.tsort=a.fn.tinysort})(jQuery);
