/*
 * XenForo album_thumbs.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
/*
 Flickbook - v0.2.0 - 2013-01-24
 Copyright (c) 2013 Rhys Evans; Licensed MIT */
!function(c,k,l,m){XenForo.MediaGallery={AlbumThumbs:function(b){b.flickbook({images:b.data("images"),speed:b.data("speed")?b.data("speed"):700,keepOriginalImage:b.data("keeporig")?b.data("keeporig"):!0,onStop:b.data("onstop")?b.data("onstop"):"reset",random:b.data("random")?b.data("random"):!1})}};XenForo.register(".AlbumThumbs","XenForo.MediaGallery.AlbumThumbs")}(jQuery,this,document);
(function(c,k,l,m){function b(a,d){this.el=a;this.$el=c(a);this.opts=d;this._name="flickbook";this.init()}function n(a){var d=a.startEvent.split(" ").sort(),b=a.stopEvent.split(" ").sort(),c=[],f=[],g=0,p=d.length;a:for(;g<p;g++){for(var h=0,e=b.length;h<e;h++)if(d[g]===b[h]){f.push(d[g]);b.splice(h,1);continue a}c.push(d[g])}a.startEvent=c.join(" ");a.stopEvent=b.join(" ");a.stopStartEvent=f.join(" ")}var e=c.fn.on?"on":"bind";b.prototype.playing=!1;b.prototype.index=-1;b.prototype.init=function(){var a=
this,d=this.$el.data("flickbook-images");this.imageSrcs=d?d:c.isArray(this.opts.images)?this.opts.images.slice():this.opts.images;"string"===typeof this.imageSrcs?this.imageSrcs=this.imageSrcs.split(","):this.imageSrcs&&!c.isArray(this.imageSrcs)&&"object"===typeof this.imageSrcs&&this.imageSrcs.start&&this.imageSrcs.end&&this._getImageIndexesFromRange();c.isArray(this.imageSrcs)&&this.imageSrcs.length?(this.imageCount=this.imageSrcs.length,this.fetchImages(),this.$el.data("flickbook-images",this.images),
this.$el[e]("start.flickbook",c.proxy(this,"start"))[e]("stop.flickbook",c.proxy(this,"stop"))[e](this.opts.stopEvent,function(){a.$el.trigger("stop.flickbook")})[e](this.opts.startEvent,function(){a.$el.trigger("start.flickbook")})[e](this.opts.stopStartEvent,function(){a.playing?a.$el.trigger("stop.flickbook"):a.$el.trigger("start.flickbook")}),this.opts.autoStart&&this.start()):this.aborted=!0};b.prototype._getImageIndexesFromRange=function(){for(var a=this,d=function(){var d=a.imageSrcs.padTo;
return d?function(a){a+="";var b=d-a.length;if(b)for(;b--;)a="0"+a;return a}:function(a){return a+""}}(),b=this.imageSrcs.end,c=[],f=this.imageSrcs.start;f<=b;f++)c.push(d(f));this.imageSrcs=c};b.prototype.start=function(){var a=this,d;this.playing||(this.to=setInterval(function(){if(a.opts.random)for(d=a.index;d===a.index;)a.index=Math.floor(Math.random()*a.imageCount);else a.index=(a.index+1)%a.imageCount;a.showImage()},this.opts.speed),this.playing=!0)};b.prototype.stop=function(){this.playing&&
(clearInterval(this.to),"reset"===this.opts.onStop&&(this.index=0),this.showImage(),this.playing=!1)};b.prototype.showImage=function(){for(var a=0;!this.images[this.index]&&a<this.imageCount;)this.index=(this.index+1)%this.imageCount,a++;this.$el.attr("src",this.images[this.index])};b.prototype.loadImage=function(a,d){var b=this;c('<img src="'+b.imageSrcs[a]+'">').load(function(){b.images[a+d]=b.imageSrcs[a];c.fn.flickbook.fetchedImages[b.imageSrcs[a]]=!0})};b.prototype.processImageSrcs=function(){for(var a=
this,b=function(){return a.opts.imageTemplate.match("{{}}")?function(b){return a.opts.imageTemplate.replace("{{}}",b)}:function(b){return a.opts.imageTemplate+b}}(),c=0,e=this.imageCount;c<e;c++)this.imageSrcs[c]=b(this.imageSrcs[c])};b.prototype.fetchImages=function(){var a=0,b=this.$el.attr("src");this.images=[];this.opts.imageTemplate&&this.processImageSrcs();this.opts.keepOriginalImage&&b!==this.imageSrcs[0]&&(this.images[0]=b,c.fn.flickbook.fetchedImages[b]=!0,a=1);b=0;for(var e=this.imageSrcs.length;b<
e;b++)c.fn.flickbook.fetchedImages[this.imageSrcs[b]]?this.images[b+a]=this.imageSrcs[b]:this.loadImage(b,a)};c.fn.flickbook=function(a){a=c.extend({},c.fn.flickbook.defaults,a);n(a);return this.each(function(){if(!c.data(this,"plugin_flickbook")){var d=new b(this,a);d.aborted||c.data(this,"plugin_flickbook",d)}})};c.fn.flickbook.fetchedImages={};c.fn.flickbook.defaults={images:null,speed:100,imageTemplate:"",startEvent:"mouseover",stopEvent:"mouseout",autoStart:!1,onStop:"reset",keepOriginalImage:!1,
random:!1}})(jQuery,window,document);
