/*
 * XenForo category_list.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,d){a instanceof String&&(a=String(a));for(var c=a.length,b=0;b<c;b++){var f=a[b];if(e.call(d,f,b,a))return{i:b,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,d){a!=Array.prototype&&a!=Object.prototype&&(a[e]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,e,d,c){if(e){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var b=a[c];b in d||(d[b]={});d=d[b]}a=a[a.length-1];c=d[a];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");!function(a,e,d,c){XenForo.CategoryList=function(a){this.__construct(a)};XenForo.CategoryList.prototype={__construct:function(a){a.sapling();"collapsibleExpanded"==a.data("liststyle")&&a.data("sapling").expand()}};XenForo.register(".CategoryList","XenForo.CategoryList")}(jQuery,this,document);
(function(a,e,d,c){a.sapling=function(d,e){var c=this,b=a(d),f={multiexpand:!0,animation:!1},g=function(a){a.addClass("sapling-expanded")},h=function(a){a.removeClass("sapling-expanded")},k=function(d){"A"!==d.target.nodeName&&(a(this).hasClass("sapling-expanded")?h(a(this)):(c.settings.multiexpand||b.find(".sapling-expanded").not(a(this).parents()).trigger("click"),g(a(this))))};c.settings={};c.init=function(){c.settings=a.extend({},f,e);c.settings.animation&&(g=function(a){a.children("ul, ol").slideDown(function(){a.addClass("sapling-expanded")})},
h=function(a){a.children("ul, ol").slideUp(function(){a.removeClass("sapling-expanded")})});b.addClass("sapling-list");b.children("li").addClass("sapling-top-level");b.find("li").each(function(){var b=a(this),c=b.children("ul, ol");-1!==c.index()&&(b.addClass("sapling-item"),b.bind("click.sapling",k),c.bind("click.sapling",function(a){if("A"!=a.target.nodeName)return!1}))})};c.expand=function(){g(b.find(".sapling-item"))};c.collapse=function(){h(b.find(".sapling-expanded"))};c.destroy=function(){b.removeClass("sapling-list");
b.children("li").removeClass("sapling-top-level");b.find("li").each(function(){var b=a(this),c=b.children("ul, ol");-1!==c.index()&&(b.removeClass("sapling-item"),b.unbind(".sapling"),c.removeAttr("style"),c.unbind(".sapling"))});b.find(".sapling-expanded").removeClass("sapling-expanded");b.data("sapling",null)};c.init()};a.fn.sapling=function(b){return this.each(function(){var d=a(this).data("sapling");if(d===c||null===d)d=new a.sapling(this,b),a(this).data("sapling",d)})}})(jQuery,window,document);
