/*
 * XenForo media_content_tag.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,f,e){a instanceof String&&(a=String(a));for(var b=a.length,c=0;c<b;c++){var d=a[c];if(f.call(e,d,c,a))return{i:c,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,e){a!=Array.prototype&&a!=Object.prototype&&(a[f]=e.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,f,e,b){if(f){e=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var c=a[b];c in e||(e[c]={});e=e[c]}a=a[a.length-1];b=e[a];f=f(b);f!=b&&null!=f&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");
!function(a,f,e,b){XenForo.XenGalleryTag=function(a){this.__construct(a)};XenForo.XenGalleryTag.prototype={__construct:function(c){c.tagsInput({width:"",minInputWidth:"100%",maxInputWidth:"100%",height:"",defaultText:"",removeWithBackspace:!0,autosize:!1,unique:!0});var d=a("#ctrl_tags_tag");XenForo.create("XenForo.AutoComplete",d);d.on("AutoComplete",function(a,b){d.val("");c.addTag(b.inserted,{unique:!0})});d.closest("form").on("submit AutoValidationBeforeSubmit",function(){var a=d.val();a.length&&
(c.addTag(a,{unique:!0}),d.val(""))})}};XenForo.register("input.Tags","XenForo.XenGalleryTag")}(jQuery,this,document);
(function(a){var f=[],e=[];a.fn.doAutosize=function(b){var c=a(this).data("minwidth"),d=a(this).data("maxwidth"),g="",e=a(this),k=a("#"+a(this).data("tester_id"));g!==(g=e.val())&&(g=g.replace(/&/g,"&amp;").replace(/\s/g," ").replace(/</g,"&lt;").replace(/>/g,"&gt;"),k.html(g),k=k.width(),b=k+b.comfortZone>=c?k+b.comfortZone:c,k=e.width(),(b<k&&b>=c||b>c&&b<d)&&e.width(b))};a.fn.resetAutosize=function(b){var c=a(this).data("minwidth")||b.minInputWidth||a(this).width();b=a(this).data("maxwidth")||
b.maxInputWidth||a(this).closest(".tagsInput").width()-b.inputPadding;var d=a(this),g=a("<tester/>").css({position:"absolute",top:-9999,left:-9999,width:"auto",fontSize:d.css("fontSize"),fontFamily:d.css("fontFamily"),fontWeight:d.css("fontWeight"),letterSpacing:d.css("letterSpacing"),whiteSpace:"nowrap"}),e=a(this).attr("id")+"_autosize_tester";0< !a("#"+e).length&&(g.attr("id",e),g.appendTo("body"));d.data("minwidth",c);d.data("maxwidth",b);d.data("tester_id",e);d.css("width",c)};a.fn.addTag=function(b,
c){c=jQuery.extend({focus:!1,callback:!0},c);this.each(function(){var d=a(this).attr("id"),g=a(this).val().split(f[d]);""==g[0]&&(g=[]);b=jQuery.trim(b);if(c.unique){var h=a(this).tagExist(b);1==h&&a("#"+d+"_tag").addClass("not_valid")}else h=!1;if(""!=b&&1!=h&&(a("<span>").addClass("tag").append(a("<span>").html('<i class="fa fa-tag fa-lg"></i>'),a("<span>").text(b).append("&nbsp;&nbsp;"),a("<a>",{href:"#",title:"",text:"x"}).click(function(){return a("#"+d).removeTag(escape(b))})).insertBefore("#"+
d+"_addTag"),g.push(b),a("#"+d+"_tag").val(""),c.focus?a("#"+d+"_tag").focus():a("#"+d+"_tag").blur(),a.fn.tagsInput.updateTagsField(this,g),c.callback&&e[d]&&e[d].onAddTag&&(h=e[d].onAddTag,h.call(this,b)),e[d]&&e[d].onChange)){var k=g.length;h=e[d].onChange;h.call(this,a(this),g[k-1])}});return!1};a.fn.removeTag=function(b){b=unescape(b);this.each(function(){var c=a(this).attr("id"),d=a(this).val().split(f[c]);a("#"+c+"_tagsinput .tag").remove();str="";for(i=0;i<d.length;i++)d[i]!=b&&(str=str+f[c]+
d[i]);a.fn.tagsInput.importTags(this,str);e[c]&&e[c].onRemoveTag&&e[c].onRemoveTag.call(this,b)});return!1};a.fn.tagExist=function(b){var c=a(this).attr("id");c=a(this).val().split(f[c]);return 0<=jQuery.inArray(b,c)};a.fn.importTags=function(b){id=a(this).attr("id");a("#"+id+"_tagsinput .tag").remove();a.fn.tagsInput.importTags(this,b)};a.fn.tagsInput=function(b){var c=jQuery.extend({interactive:!0,defaultText:"add a tag",minChars:0,width:"300px",height:"100px",autocomplete:{selectFirst:!1},hide:!0,
delimiter:",",unique:!0,removeWithBackspace:!0,autosize:!0,comfortZone:20,inputPadding:12},b);this.each(function(){c.hide&&a(this).hide();var d=a(this).attr("id");if(!d||f[a(this).attr("id")])d=a(this).attr("id","tags"+(new Date).getTime()).attr("id");var b=jQuery.extend({pid:d,real_input:"#"+d,holder:"#"+d+"_tagsinput",input_wrapper:"#"+d+"_addTag",fake_input:"#"+d+"_tag"},c);f[d]=b.delimiter;if(c.onAddTag||c.onRemoveTag||c.onChange)e[d]=[],e[d].onAddTag=c.onAddTag,e[d].onRemoveTag=c.onRemoveTag,
e[d].onChange=c.onChange;var h='<div id="'+d+'_tagsinput" class="tagsInput textCtrl"><div id="'+d+'_addTag">';c.interactive&&(h=h+'<input id="'+d+'_tag" value="" class="AcSingle" data-acurl="index.php?xengallery/tagging/auto-complete" data-default="'+c.defaultText+'" />');a(h+'</div><div class="tagsClear"></div></div>').insertAfter(this);a(b.holder).css("width",c.width);a(b.holder).css("min-height",c.height);a(b.holder).css("height","100%");""!=a(b.real_input).val()&&a.fn.tagsInput.importTags(a(b.real_input),
a(b.real_input).val());if(c.interactive){a(b.fake_input).val(a(b.fake_input).attr("data-default"));a(b.fake_input).resetAutosize(c);a(b.holder).bind("click",b,function(b){a(b.data.fake_input).focus()});a(b.fake_input).bind("focus",b,function(b){a(b.data.fake_input).val()==a(b.data.fake_input).attr("data-default")&&a(b.data.fake_input).val("")});if(void 0!=c.autocomplete_url){autocomplete_options={source:c.autocomplete_url};for(attrname in c.autocomplete)autocomplete_options[attrname]=c.autocomplete[attrname];
void 0!==jQuery.Autocompleter?(a(b.fake_input).autocomplete(c.autocomplete_url,c.autocomplete),a(b.fake_input).bind("result",b,function(b,e,f){e&&a("#"+d).addTag(e[0]+"",{focus:!0,unique:c.unique})})):void 0!==jQuery.ui.autocomplete&&(a(b.fake_input).autocomplete(autocomplete_options),a(b.fake_input).bind("autocompleteselect",b,function(b,d){a(b.data.real_input).addTag(d.item.value,{focus:!0,unique:c.unique});return!1}))}a(b.fake_input).bind("keypress",b,function(b){if(b.which==b.data.delimiter.charCodeAt(0)||
13==b.which)return b.preventDefault(),b.data.minChars<=a(b.data.fake_input).val().length&&(!b.data.maxChars||b.data.maxChars>=a(b.data.fake_input).val().length)&&a(b.data.real_input).addTag(a(b.data.fake_input).val(),{focus:!0,unique:c.unique}),a(b.data.fake_input).resetAutosize(c),!1;b.data.autosize&&a(b.data.fake_input).doAutosize(c)});b.removeWithBackspace&&a(b.fake_input).bind("keydown",function(b){if(8==b.keyCode&&""==a(this).val()){b.preventDefault();b=a(this).closest(".tagsInput").find(".tag:last").text();
var c=a(this).attr("id").replace(/_tag$/,"");b=b.replace(/[\s]+x$/,"");a("#"+c).removeTag(escape(b));a(this).trigger("focus")}});a(b.fake_input).blur();b.unique&&a(b.fake_input).keydown(function(b){(8==b.keyCode||String.fromCharCode(b.which).match(/\w+|[\u00e1\u00e9\u00ed\u00f3\u00fa\u00c1\u00c9\u00cd\u00d3\u00da\u00f1\u00d1,/]+/))&&a(this).removeClass("notValid")})}});return this};a.fn.tagsInput.updateTagsField=function(b,c){var d=a(b).attr("id");a(b).val(c.join(f[d]))};a.fn.tagsInput.importTags=
function(b,c){a(b).val("");var d=a(b).attr("id");c=c.split(f[d]);for(i=0;i<c.length;i++)a(b).addTag(c[i],{focus:!1,callback:!1});e[d]&&e[d].onChange&&e[d].onChange.call(b,b,c[i])}})(jQuery);
