/*
 * XenForo media_lightbox.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
/*
 Magnific Popup - v0.9.9 - 2013-11-25
 http://dimsemenov.com/plugins/magnific-popup/
 Copyright (c) 2013 Dmitry Semenov; */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,a,f){d instanceof String&&(d=String(d));for(var m=d.length,h=0;h<m;h++){var q=d[h];if(a.call(f,q,h,d))return{i:h,v:q}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,a,f){d!=Array.prototype&&d!=Object.prototype&&(d[a]=f.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,a,f,m){if(a){f=$jscomp.global;d=d.split(".");for(m=0;m<d.length-1;m++){var h=d[m];h in f||(f[h]={});f=f[h]}d=d[d.length-1];m=f[d];a=a(m);a!=m&&null!=a&&$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");
!function(d,a,f,m){XenForo.XenGalleryLightbox=function(a){this.__construct(a)};XenForo.XenGalleryLightbox.prototype={__construct:function(a){this.element||(this.element=a);d(".mediaContainer .Image").click(function(){d(".LightboxContainer a.Lightbox").click()});d.extend(!0,d.magnificPopup.defaults,{tClose:XenForo.phrases.xengallery_lightbox_close,tLoading:XenForo.phrases.xengallery_lightbox_loading,gallery:{tPrev:XenForo.phrases.xengallery_lightbox_previous,tNext:XenForo.phrases.xengallery_lightbox_next,
tCounter:XenForo.phrases.xengallery_lightbox_counter},image:{tError:XenForo.phrases.xengallery_lightbox_error},ajax:{tError:XenForo.phrases.xengallery_lightbox_error}});$self=this;a.magnificPopup({gallery:{enabled:!0,preload:0},type:a.data("type"),delegate:".Lightbox",image:{titleSrc:function(a){var d=XenForo.htmlspecialchars(a.el.data("media-title").toString()),h=XenForo.htmlspecialchars(a.el.data("media-url").toString());a=XenForo.htmlspecialchars(a.el.data("username").toString());return'<a href="'+
h+'">'+d+'</a><small><a href="'+h+'">'+a+"</a></small>"}},callbacks:{beforeOpen:function(){this.totalCount=parseInt($self.element.data("total-count"))},open:function(){if(!$self.element.hasClass("LightboxOpenFired"))return this.limit=50,$self.performAjax(this.limit)},beforeChange:function(){if(this.$previousItem=this.currItem)this.$previousItem=this.$previousItem.el.data("img-index")},change:function(a){if(this.$previousItem&&(a=this.currItem)){a=a.el.data("img-index");var h="next",f=this.limit/2,
q=!1,m=this.items.length,x=0;a<this.$previousItem&&(h="prev");switch(h){case "prev":a<f&&(d(".LightboxNoMorePrev").length||(q=!0),x=d(".Lightbox").first().data("media-id"));break;case "next":a>m-f&&(d(".LightboxNoMoreNext").length||(q=!0),x=d(".Lightbox").last().data("media-id"))}if(q)return $self.performAjax(f,h,x)}}},iframe:{markup:'<div class="mfp-iframe-scaler iframe mfp-figure"><div class="mfp-close"></div><iframe class="mfp-iframe" src="//about:blank" frameborder="0" allowfullscreen></iframe><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></div>'}})},
performAjax:function(a,f,m){this.element.addClass("LightboxOpenFired");a={limit:a,direction:f};m&&(a.last_media_id=m);XenForo.ajax(this.element.data("fetch-url"),a,d.context(this,"ajaxSuccess"))},ajaxSuccess:function(a){a.prevTemplateHtml&&d(a.prevTemplateHtml).prependTo(this.element);a.nextTemplateHtml&&d(a.nextTemplateHtml).appendTo(this.element);this.element.magnificPopup("open",d.magnificPopup.instance.index);this.reindexInputs()},reindexInputs:function(){var a=0;d(".Lightbox").each(function(){a++;
d(this).data("img-index",a)})}};XenForo.register(".LightboxContainer","XenForo.XenGalleryLightbox")}(jQuery,this,document);
(function(d){var a,f=function(){},m=!!window.jQuery,h,q=d(window),v,r,z,w,x,k=function(b,c){a.ev.on("mfp"+b+".mfp",c)},p=function(a,c,e,g){var b=document.createElement("div");b.className="mfp-"+a;e&&(b.innerHTML=e);g?c&&c.appendChild(b):(b=d(b),c&&b.appendTo(c));return b},l=function(b,c){a.ev.triggerHandler("mfp"+b,c);a.st.callbacks&&(b=b.charAt(0).toLowerCase()+b.slice(1),a.st.callbacks[b]&&a.st.callbacks[b].apply(a,d.isArray(c)?c:[c]))},C=function(b){b===x&&a.currTemplate.closeBtn||(a.currTemplate.closeBtn=
d(a.st.closeMarkup.replace("%title%",a.st.tClose)),x=b);return a.currTemplate.closeBtn},D=function(){d.magnificPopup.instance||(a=new f,a.init(),d.magnificPopup.instance=a)},L=function(){var a=document.createElement("p").style,c=["ms","O","Moz","Webkit"];if(void 0!==a.transition)return!0;for(;c.length;)if(c.pop()+"Transition"in a)return!0;return!1};f.prototype={constructor:f,init:function(){var b=navigator.appVersion;a.isIE7=-1!==b.indexOf("MSIE 7.");a.isIE8=-1!==b.indexOf("MSIE 8.");a.isLowIE=a.isIE7||
a.isIE8;a.isAndroid=/android/gi.test(b);a.isIOS=/iphone|ipad|ipod/gi.test(b);a.supportsTransition=L();a.probablyMobile=a.isAndroid||a.isIOS||/(Opera Mini)|Kindle|webOS|BlackBerry|(Opera Mobi)|(Windows Phone)|IEMobile/i.test(navigator.userAgent);v=d(document.body);r=d(document);a.popupsCache={}},open:function(b){var c;if(!1===b.isObj){a.items=b.items.toArray();a.index=0;var e=b.items;for(c=0;c<e.length;c++){var g=e[c];g.parsed&&(g=g.el[0]);if(g===b.el[0]){a.index=c;break}}}else a.items=d.isArray(b.items)?
b.items:[b.items],a.index=b.index||0;if(a.isOpen)a.updateItemHTML();else{a.types=[];w="";a.ev=b.mainEl&&b.mainEl.length?b.mainEl.eq(0):r;b.key?(a.popupsCache[b.key]||(a.popupsCache[b.key]={}),a.currTemplate=a.popupsCache[b.key]):a.currTemplate={};a.st=d.extend(!0,{},d.magnificPopup.defaults,b);a.fixedContentPos="auto"===a.st.fixedContentPos?!a.probablyMobile:a.st.fixedContentPos;a.st.modal&&(a.st.closeOnContentClick=!1,a.st.closeOnBgClick=!1,a.st.showCloseBtn=!1,a.st.enableEscapeKey=!1);a.bgOverlay||
(a.bgOverlay=p("bg").on("click.mfp",function(){a.close()}),a.wrap=p("wrap").attr("tabindex",-1).on("click.mfp",function(b){a._checkIfClose(b.target)&&a.close()}),a.container=p("container",a.wrap));a.contentContainer=p("content");a.st.preloader&&(a.preloader=p("preloader",a.container,a.st.tLoading));e=d.magnificPopup.modules;for(c=0;c<e.length;c++)g=e[c],g=g.charAt(0).toUpperCase()+g.slice(1),a["init"+g].call(a);l("BeforeOpen");a.st.showCloseBtn&&(a.st.closeBtnInside?(k("MarkupParse",function(a,b,
c,e){c.close_replaceWith=C(e.type)}),w+=" mfp-close-btn-in"):a.wrap.append(C()));a.st.alignTop&&(w+=" mfp-align-top");a.fixedContentPos?a.wrap.css({overflow:a.st.overflowY,overflowX:"hidden",overflowY:a.st.overflowY}):a.wrap.css({top:q.scrollTop(),position:"absolute"});(!1===a.st.fixedBgPos||"auto"===a.st.fixedBgPos&&!a.fixedContentPos)&&a.bgOverlay.css({height:r.height(),position:"absolute"});if(a.st.enableEscapeKey)r.on("keyup.mfp",function(b){27===b.keyCode&&a.close()});q.on("resize.mfp",function(){a.updateSize()});
a.st.closeOnContentClick||(w+=" mfp-auto-cursor");w&&a.wrap.addClass(w);c=a.wH=q.height();e={};a.fixedContentPos&&a._hasScrollBar(c)&&a._getScrollbarSize();a.fixedContentPos&&(a.isIE7?d("body, html").css("overflow","hidden"):e.overflow="hidden");g=a.st.mainClass;a.isIE7&&(g+=" mfp-ie7");g&&a._addClassToMFP(g);a.updateItemHTML();l("BuildControls");d("html").css(e);a.bgOverlay.add(a.wrap).prependTo(document.body);a._lastFocusedEl=document.activeElement;setTimeout(function(){a.content?(a._addClassToMFP("mfp-ready"),
a._setFocus()):a.bgOverlay.addClass("mfp-ready");r.on("focusin.mfp",a._onFocusIn)},16);a.isOpen=!0;a.updateSize(c);l("Open");return b}},close:function(){a.isOpen&&(l("BeforeClose"),a.isOpen=!1,a.st.removalDelay&&!a.isLowIE&&a.supportsTransition?(a._addClassToMFP("mfp-removing"),setTimeout(function(){a._close()},a.st.removalDelay)):a._close())},_close:function(){l("Close");var b="mfp-removing mfp-ready ";a.bgOverlay.detach();a.wrap.detach();a.container.empty();a.st.mainClass&&(b+=a.st.mainClass+" ");
a._removeClassFromMFP(b);a.fixedContentPos&&(b={marginRight:""},a.isIE7?d("body, html").css("overflow",""):b.overflow="",d("html").css(b));r.off("keyup.mfp focusin.mfp");a.ev.off(".mfp");a.wrap.attr("class","mfp-wrap").removeAttr("style");a.bgOverlay.attr("class","mfp-bg");a.container.attr("class","mfp-container");!a.st.showCloseBtn||a.st.closeBtnInside&&!0!==a.currTemplate[a.currItem.type]||a.currTemplate.closeBtn&&a.currTemplate.closeBtn.detach();a._lastFocusedEl&&d(a._lastFocusedEl).focus();a.currItem=
null;a.content=null;a.currTemplate=null;a.prevHeight=0;l("AfterClose")},updateSize:function(b){a.isIOS?(b=document.documentElement.clientWidth/window.innerWidth*window.innerHeight,a.wrap.css("height",b),a.wH=b):a.wH=b||q.height();a.fixedContentPos||a.wrap.css("height",a.wH);l("Resize")},updateItemHTML:function(){var b=a.items[a.index];a.contentContainer.detach();a.content&&a.content.detach();b.parsed||(b=a.parseEl(a.index));var c=b.type;l("BeforeChange",[a.currItem?a.currItem.type:"",c]);a.currItem=
b;if(!a.currTemplate[c]){var e=a.st[c]?a.st[c].markup:!1;l("FirstMarkupParse",e);a.currTemplate[c]=e?d(e):!0}z&&z!==b.type&&a.container.removeClass("mfp-"+z+"-holder");e=a["get"+c.charAt(0).toUpperCase()+c.slice(1)](b,a.currTemplate[c]);a.appendContent(e,c);b.preloaded=!0;l("Change",b);z=b.type;a.container.prepend(a.contentContainer);l("AfterChange")},appendContent:function(b,c){(a.content=b)?a.st.showCloseBtn&&a.st.closeBtnInside&&!0===a.currTemplate[c]?a.content.find(".mfp-close").length||a.content.append(C()):
a.content=b:a.content="";l("BeforeAppend");a.container.addClass("mfp-"+c+"-holder");a.contentContainer.append(a.content)},parseEl:function(b){var c=a.items[b],e=c.type;c=c.tagName?{el:d(c)}:{data:c,src:c.src};if(c.el){for(var g=a.types,n=0;n<g.length;n++)if(c.el.hasClass("mfp-"+g[n])){e=g[n];break}c.src=c.el.attr("data-mfp-src");c.src||(c.src=c.el.attr("href"))}c.type=e||a.st.type||"inline";c.index=b;c.parsed=!0;a.items[b]=c;l("ElementParse",c);return a.items[b]},addGroup:function(b,c){var e=function(e){e.mfpEl=
this;a._openClick(e,b,c)};c||(c={});c.mainEl=b;if(c.items)c.isObj=!0,b.off("click.magnificPopup").on("click.magnificPopup",e);else if(c.isObj=!1,c.delegate)b.off("click.magnificPopup").on("click.magnificPopup",c.delegate,e);else c.items=b,b.off("click.magnificPopup").on("click.magnificPopup",e)},_openClick:function(b,c,e){if((void 0!==e.midClick?e.midClick:d.magnificPopup.defaults.midClick)||2!==b.which&&!b.ctrlKey&&!b.metaKey){var g=void 0!==e.disableOn?e.disableOn:d.magnificPopup.defaults.disableOn;
if(g)if(d.isFunction(g)){if(!g.call(a))return!0}else if(q.width()<g)return!0;b.type&&(b.preventDefault(),a.isOpen&&b.stopPropagation());e.el=d(b.mfpEl);e.delegate&&(e.items=c.find(e.delegate));a.open(e)}},updateStatus:function(b,c){a.preloader&&(h!==b&&a.container.removeClass("mfp-s-"+h),c||"loading"!==b||(c=a.st.tLoading),c={status:b,text:c},l("UpdateStatus",c),b=c.status,c=c.text,a.preloader.html(c),a.preloader.find("a").on("click",function(a){a.stopImmediatePropagation()}),a.container.addClass("mfp-s-"+
b),h=b)},_checkIfClose:function(b){if(!d(b).hasClass("mfp-prevent-close")){var c=a.st.closeOnContentClick,e=a.st.closeOnBgClick;if(c&&e||!a.content||d(b).hasClass("mfp-close")||a.preloader&&b===a.preloader[0])return!0;if(b!==a.content[0]&&!d.contains(a.content[0],b)){if(e&&d.contains(document,b))return!0}else if(c)return!0;return!1}},_addClassToMFP:function(b){a.bgOverlay.addClass(b);a.wrap.addClass(b)},_removeClassFromMFP:function(b){this.bgOverlay.removeClass(b);a.wrap.removeClass(b)},_hasScrollBar:function(b){return(a.isIE7?
r.height():document.body.scrollHeight)>(b||q.height())},_setFocus:function(){(a.st.focus?a.content.find(a.st.focus).eq(0):a.wrap).focus()},_onFocusIn:function(b){if(b.target!==a.wrap[0]&&!d.contains(a.wrap[0],b.target))return a._setFocus(),!1},_parseMarkup:function(a,c,e){var b;e.data&&(c=d.extend(e.data,c));l("MarkupParse",[a,c,e]);d.each(c,function(c,e){if(void 0===e||!1===e)return!0;b=c.split("_");if(1<b.length){if(c=a.find(".mfp-"+b[0]),0<c.length){var d=b[1];"replaceWith"===d?c[0]!==e[0]&&c.replaceWith(e):
"img"===d?c.is("img")?c.attr("src",e):c.replaceWith('<img src="'+e+'" class="'+c.attr("class")+'" />'):c.attr(b[1],e)}}else a.find(".mfp-"+c).html(e)})},_getScrollbarSize:function(){if(void 0===a.scrollbarSize){var b=document.createElement("div");b.id="mfp-sbm";b.style.cssText="width: 99px; height: 99px; overflow: scroll; position: absolute; top: -9999px;";document.body.appendChild(b);a.scrollbarSize=b.offsetWidth-b.clientWidth;document.body.removeChild(b)}return a.scrollbarSize}};d.magnificPopup=
{instance:null,proto:f.prototype,modules:[],open:function(a,c){D();a=a?d.extend(!0,{},a):{};a.isObj=!0;a.index=c||0;return this.instance.open(a)},close:function(){return d.magnificPopup.instance&&d.magnificPopup.instance.close()},registerModule:function(a,c){c.options&&(d.magnificPopup.defaults[a]=c.options);d.extend(this.proto,c.proto);this.modules.push(a)},defaults:{disableOn:0,key:null,midClick:!1,mainClass:"",preloader:!0,focus:"",closeOnContentClick:!1,closeOnBgClick:!0,closeBtnInside:!0,showCloseBtn:!0,
enableEscapeKey:!0,modal:!1,alignTop:!1,removalDelay:0,fixedContentPos:"auto",fixedBgPos:"auto",overflowY:"auto",closeMarkup:'<button title="%title%" type="button" class="mfp-close">&times;</button>',tClose:"Close (Esc)",tLoading:"Loading..."}};d.fn.magnificPopup=function(b){D();var c=d(this);if("string"===typeof b)if("open"===b){var e=m?c.data("magnificPopup"):c[0].magnificPopup,g=parseInt(arguments[1],10)||0;if(e.items)var n=e.items[g];else n=c,e.delegate&&(n=n.find(e.delegate)),n=n.eq(g);a._openClick({mfpEl:n},
c,e)}else a.isOpen&&a[b].apply(a,Array.prototype.slice.call(arguments,1));else b=d.extend(!0,{},b),m?c.data("magnificPopup",b):c[0].magnificPopup=b,a.addGroup(c,b);return c};var y,A,B,H=function(){B&&(A.after(B.addClass(y)).detach(),B=null)};d.magnificPopup.registerModule("inline",{options:{hiddenClass:"hide",markup:"",tNotFound:"Content not found"},proto:{initInline:function(){a.types.push("inline");k("Close.inline",function(){H()})},getInline:function(b,c){H();if(b.src){c=a.st.inline;var e=d(b.src);
if(e.length){var g=e[0].parentNode;g&&g.tagName&&(A||(y=c.hiddenClass,A=p(y),y="mfp-"+y),B=e.after(A).detach().removeClass(y));a.updateStatus("ready")}else a.updateStatus("error",c.tNotFound),e=d("<div>");return b.inlineElement=e}a.updateStatus("ready");a._parseMarkup(c,{},b);return c}}});var t,I=function(){t&&v.removeClass(t);a.req&&a.req.abort()};d.magnificPopup.registerModule("ajax",{options:{settings:null,cursor:"mfp-ajax-cur",tError:'<a href="%url%">The content</a> could not be loaded.'},proto:{initAjax:function(){a.types.push("ajax");
t=a.st.ajax.cursor;k("Close.ajax",I);k("BeforeChange.ajax",I)},getAjax:function(b){t&&v.addClass(t);a.updateStatus("loading");var c=d.extend({url:b.src,success:function(c,g,n){c={data:c,xhr:n};l("ParseAjax",c);a.appendContent(d(c.data),"ajax");b.finished=!0;t&&v.removeClass(t);a._setFocus();setTimeout(function(){a.wrap.addClass("mfp-ready")},16);a.updateStatus("ready");l("AjaxContentAdded")},error:function(){t&&v.removeClass(t);b.finished=b.loadError=!0;a.updateStatus("error",a.st.ajax.tError.replace("%url%",
b.src))}},a.st.ajax.settings);a.req=d.ajax(c);return""}}});var u,J=function(b){if(b.data&&void 0!==b.data.title)return b.data.title;var c=a.st.image.titleSrc;if(c){if(d.isFunction(c))return c.call(a,b);if(b.el)return b.el.attr(c)||""}return""};d.magnificPopup.registerModule("image",{options:{markup:'<div class="mfp-figure"><div class="mfp-close"></div><figure><div class="mfp-img"></div><figcaption><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></figcaption></figure></div>',
cursor:"mfp-zoom-out-cur",titleSrc:"title",verticalFit:!0,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',arrows:!0,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",tError:'<a href="%url%">The image</a> could not be loaded.'},proto:{initImage:function(){var b=a.st.image;a.types.push("image");k("Open.image",function(){"image"===a.currItem.type&&b.cursor&&v.addClass(b.cursor)});k("Close.image",function(){b.cursor&&v.removeClass(b.cursor);
q.off("resize.mfp")});k("Resize.image",a.resizeImage);a.isLowIE&&k("AfterChange",a.resizeImage)},resizeImage:function(){var b=a.currItem;if(b&&b.img&&a.st.image.verticalFit){var c=0;a.isLowIE&&(c=parseInt(b.img.css("padding-top"),10)+parseInt(b.img.css("padding-bottom"),10));b.img.css("max-height",a.wH-c)}},_onImageHasSize:function(b){b.img&&(b.hasSize=!0,u&&clearInterval(u),b.isCheckingImgSize=!1,l("ImageHasSize",b),b.imgHidden&&(a.content&&a.content.removeClass("mfp-loading"),b.imgHidden=!1))},
findImageSize:function(b){var c=0,e=b.img[0],d=function(g){u&&clearInterval(u);u=setInterval(function(){0<e.naturalWidth?a._onImageHasSize(b):(200<c&&clearInterval(u),c++,3===c?d(10):40===c?d(50):100===c&&d(500))},g)};d(1)},getImage:function(b,c){var e=0,g=function(){b&&(b.img[0].complete?(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("ready")),b.hasSize=!0,b.loaded=!0,l("ImageLoadComplete")):(e++,200>e?setTimeout(g,100):n()))},n=function(){b&&(b.img.off(".mfploader"),
b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("error",f.tError.replace("%url%",b.src))),b.hasSize=!0,b.loaded=!0,b.loadError=!0)},f=a.st.image,k=c.find(".mfp-img");if(k.length){var h=document.createElement("img");h.className="mfp-img";b.img=d(h).on("load.mfploader",g).on("error.mfploader",n);h.src=b.src;k.is("img")&&(b.img=b.img.clone());h=b.img[0];0<h.naturalWidth?b.hasSize=!0:h.width||(b.hasSize=!1)}a._parseMarkup(c,{title:J(b),img_replaceWith:b.img},b);a.resizeImage();if(b.hasSize)return u&&
clearInterval(u),b.loadError?(c.addClass("mfp-loading"),a.updateStatus("error",f.tError.replace("%url%",b.src))):(c.removeClass("mfp-loading"),a.updateStatus("ready")),c;a.updateStatus("loading");b.loading=!0;b.hasSize||(b.imgHidden=!0,c.addClass("mfp-loading"),a.findImageSize(b));return c}}});var E;d.magnificPopup.registerModule("zoom",{options:{enabled:!1,easing:"ease-in-out",duration:300,opener:function(a){return a.is("img")?a:a.find("img")}},proto:{initZoom:function(){var b=a.st.zoom,c;if(b.enabled&&
a.supportsTransition){var e=b.duration,d=function(a){a=a.clone().removeAttr("style").removeAttr("class").addClass("mfp-animated-image");var c={position:"fixed",zIndex:9999,left:0,top:0,"-webkit-backface-visibility":"hidden"};c["-webkit-transition"]=c["-moz-transition"]=c["-o-transition"]=c.transition="all "+b.duration/1E3+"s "+b.easing;a.css(c);return a},n=function(){a.content.css("visibility","visible")},h,f;k("BuildControls.zoom",function(){a._allowZoom()&&(clearTimeout(h),a.content.css("visibility",
"hidden"),(c=a._getItemToZoom())?(f=d(c),f.css(a._getOffset()),a.wrap.append(f),h=setTimeout(function(){f.css(a._getOffset(!0));h=setTimeout(function(){n();setTimeout(function(){f.remove();c=f=null;l("ZoomAnimationEnded")},16)},e)},16)):n())});k("BeforeClose.zoom",function(){if(a._allowZoom()){clearTimeout(h);a.st.removalDelay=e;if(!c){c=a._getItemToZoom();if(!c)return;f=d(c)}f.css(a._getOffset(!0));a.wrap.append(f);a.content.css("visibility","hidden");setTimeout(function(){f.css(a._getOffset())},
16)}});k("Close.zoom",function(){a._allowZoom()&&(n(),f&&f.remove(),c=null)})}},_allowZoom:function(){return"image"===a.currItem.type},_getItemToZoom:function(){return a.currItem.hasSize?a.currItem.img:!1},_getOffset:function(b){var c=b?a.currItem.img:a.st.zoom.opener(a.currItem.el||a.currItem);b=c.offset();var e=parseInt(c.css("padding-top"),10),g=parseInt(c.css("padding-bottom"),10);b.top-=d(window).scrollTop()-e;c={width:c.width(),height:(m?c.innerHeight():c[0].offsetHeight)-g-e};void 0===E&&(E=
void 0!==document.createElement("p").style.MozTransform);E?c["-moz-transform"]=c.transform="translate("+b.left+"px,"+b.top+"px)":(c.left=b.left,c.top=b.top);return c}}});var F=function(b){if(a.currTemplate.iframe){var c=a.currTemplate.iframe.find("iframe");c.length&&(b||(c[0].src="//about:blank"),a.isIE8&&c.css("display",b?"block":"none"))}};d.magnificPopup.registerModule("iframe",{options:{markup:'<div class="mfp-iframe-scaler"><div class="mfp-close"></div><iframe class="mfp-iframe" src="//about:blank" frameborder="0" allowfullscreen></iframe></div>',
srcAction:"iframe_src",patterns:{youtube:{index:"youtube.com",id:"v=",src:"//www.youtube.com/embed/%id%?autoplay=1"},vimeo:{index:"vimeo.com/",id:"/",src:"//player.vimeo.com/video/%id%?autoplay=1"},gmaps:{index:"//maps.google.",src:"%id%&output=embed"}}},proto:{initIframe:function(){a.types.push("iframe");k("BeforeChange",function(a,c,e){c!==e&&("iframe"===c?F():"iframe"===e&&F(!0))});k("Close.iframe",function(){F()})},getIframe:function(b,c){var e=b.src,g=a.st.iframe;d.each(g.patterns,function(){if(-1<
e.indexOf(this.index))return this.id&&(e="string"===typeof this.id?e.substr(e.lastIndexOf(this.id)+this.id.length,e.length):this.id.call(this,e)),e=this.src.replace("%id%",e),!1});var f={};g.srcAction&&(f[g.srcAction]=e);f.title=J(b);a._parseMarkup(c,f,b);a.updateStatus("ready");return c}}});var G=function(b){var c=a.items.length;return b>c-1?b-c:0>b?c+b:b},K=function(a,c,e){return a.replace(/%curr%/gi,c+1).replace(/%total%/gi,e)};d.magnificPopup.registerModule("gallery",{options:{enabled:!1,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',
preload:[0,2],navigateByImgClick:!0,arrows:!0,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",tCounter:"%curr% of %total%"},proto:{initGallery:function(){var b=a.st.gallery,c=!!d.fn.mfpFastClick;a.direction=!0;if(!b||!b.enabled)return!1;w+=" mfp-gallery";k("Open.mfp-gallery",function(){if(b.navigateByImgClick)a.wrap.on("click.mfp-gallery",".mfp-img",function(){if(1<a.items.length)return a.next(),!1});r.on("keydown.mfp-gallery",function(b){37===b.keyCode?a.prev():39===b.keyCode&&a.next()})});
k("UpdateStatus.mfp-gallery",function(b,c){c.text&&(b=a.items.length,a.totalCount&&(b=a.totalCount),c.text=K(c.text,a.currItem.index,b))});k("MarkupParse.mfp-gallery",function(c,d,f,h){c=a.items.length;a.totalCount&&(c=a.totalCount);f.counter=1<c?K(b.tCounter,h.index,c):""});k("BuildControls.mfp-gallery",function(){if(0<a.items.length&&b.arrows&&!a.arrowLeft){var e=b.arrowMarkup,g=a.arrowLeft=d(e.replace(/%title%/gi,b.tPrev).replace(/%dir%/gi,"left")).addClass("mfp-prevent-close");e=a.arrowRight=
d(e.replace(/%title%/gi,b.tNext).replace(/%dir%/gi,"right")).addClass("mfp-prevent-close");var f=c?"mfpFastClick":"click";g[f](function(){a.prev()});e[f](function(){a.next()});a.isIE7&&(p("b",g[0],!1,!0),p("a",g[0],!1,!0),p("b",e[0],!1,!0),p("a",e[0],!1,!0));a.container.append(g.add(e))}});k("Change.mfp-gallery",function(){a._preloadTimeout&&clearTimeout(a._preloadTimeout);a._preloadTimeout=setTimeout(function(){a.preloadNearbyImages();a._preloadTimeout=null},16)});k("Close.mfp-gallery",function(){r.off(".mfp-gallery");
a.wrap.off("click.mfp-gallery");a.arrowLeft&&c&&a.arrowLeft.add(a.arrowRight).destroyMfpFastClick();a.arrowRight=a.arrowLeft=null})},next:function(){a.direction=!0;a.index=G(a.index+1);a.updateItemHTML()},prev:function(){a.direction=!1;a.index=G(a.index-1);a.updateItemHTML()},goTo:function(b){a.direction=b>=a.index;a.index=b;a.updateItemHTML()},preloadNearbyImages:function(){var b=a.st.gallery.preload,c=Math.min(b[0],a.items.length);b=Math.min(b[1],a.items.length);var d;for(d=1;d<=(a.direction?b:
c);d++)a._preloadItem(a.index+d);for(d=1;d<=(a.direction?c:b);d++)a._preloadItem(a.index-d)},_preloadItem:function(b){b=G(b);if(!a.items[b].preloaded){var c=a.items[b];c.parsed||(c=a.parseEl(b));l("LazyLoad",c);"image"===c.type&&(c.img=d('<img class="mfp-img" />').on("load.mfploader",function(){c.hasSize=!0}).on("error.mfploader",function(){c.hasSize=!0;c.loadError=!0;l("LazyLoadError",c)}).attr("src",c.src));c.preloaded=!0}}}});d.magnificPopup.registerModule("retina",{options:{replaceSrc:function(a){return a.src.replace(/\.\w+$/,
function(a){return"@2x"+a})},ratio:1},proto:{initRetina:function(){if(1<window.devicePixelRatio){var b=a.st.retina,c=b.ratio;c=isNaN(c)?c():c;1<c&&(k("ImageHasSize.retina",function(a,b){b.img.css({"max-width":b.img[0].naturalWidth/c,width:"100%"})}),k("ElementParse.retina",function(a,d){d.src=b.replaceSrc(d,c)}))}}}});(function(){var a="ontouchstart"in window,c=function(){q.off("touchmove"+e+" touchend"+e)},e=".mfpFastClick";d.fn.mfpFastClick=function(b){return d(this).each(function(){var f=d(this),
g;if(a){var h,k,l,m,p,r;f.on("touchstart"+e,function(a){m=!1;r=1;p=a.originalEvent?a.originalEvent.touches[0]:a.touches[0];k=p.clientX;l=p.clientY;q.on("touchmove"+e,function(a){p=a.originalEvent?a.originalEvent.touches:a.touches;r=p.length;p=p[0];if(10<Math.abs(p.clientX-k)||10<Math.abs(p.clientY-l))m=!0,c()}).on("touchend"+e,function(a){c();m||1<r||(g=!0,a.preventDefault(),clearTimeout(h),h=setTimeout(function(){g=!1},1E3),b())})})}f.on("click"+e,function(){g||b()})})};d.fn.destroyMfpFastClick=
function(){d(this).off("touchstart"+e+" click"+e);a&&q.off("touchmove"+e+" touchend"+e)}})();D()})(window.jQuery||window.Zepto);
