/*
 * XenForo media_upload_new.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,l,e){a instanceof String&&(a=String(a));for(var m=a.length,g=0;g<m;g++){var p=a[g];if(l.call(e,p,g,a))return{i:g,v:p}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,l,e){a!=Array.prototype&&a!=Object.prototype&&(a[l]=e.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,l,e,m){if(l){e=$jscomp.global;a=a.split(".");for(m=0;m<a.length-1;m++){var g=a[m];g in e||(e[g]={});e=e[g]}a=a[a.length-1];m=e[a];l=l(m);l!=m&&null!=l&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");
!function(a,l,e,m){XenForo.MediaGallery={SetAllImageTitles:function(c){c.click(function(){$titles=a("#SetAllImageTitleText").val();a("#SetAllImageTitleText").val("");$titles&&a(".SetImageTitle").each(function(c,b){b=a(b);var h=$titles;h=h.replace("%f",b.data("filename"));h=h.replace("%n",c+1);a(this).val(h)})})},SetAllImageDescriptions:function(c){c.click(function(){this.titles=a("#SetAllImageDescriptionText").val();a("#SetAllImageDescriptionText").val("");this.titles&&a(".SetImageDescription").val(this.titles)})},
SetAllVideoTitles:function(c){c.click(function(){this.titles=a("#SetAllVideoTitleText").val();a("#SetAllVideoTitleText").val("");this.titles&&a(".SetVideoTitle").val(this.titles)})},SetAllVideoDescriptions:function(c){c.click(function(){this.titles=a("#SetAllVideoDescriptionText").val();a("#SetAllVideoDescriptionText").val("");this.titles&&a(".SetVideoDescription").val(this.titles)})},InsertFilename:function(c){c.click(function(d){d.preventDefault();d=c.data("filename");var b=c.data("target");a(b).val(d)})}};
XenForo.SetAllTitlesForm=function(a){a.closest("form").submit(function(a){a.preventDefault();return!1});a.overlay().close()};var g=XenForo.speed.normal,p=XenForo.speed.fast;XenForo.AttachmentDownloader=function(a){this.__construct(a)};XenForo.AttachmentDownloader.prototype={__construct:function(c){this.$input=c;this.url=c.data("href");this.uniqueKey=c.data("key");a(".DownloadTrigger").bind({click:a.context(this,"doDownload")})},doDownload:function(c){c.preventDefault();this.xhr=XenForo.ajax(this.url,
{image_url:this.$input.val()},a.context(this,"ajaxSuccess"),{error:"failure"});this.$input.val("")},ajaxSuccess:function(c){if(c.error){var d="";a.each(c.error,function(a,c){d+=c+"\n"});XenForo.alert(d);return!1}$container=a("#AttachmentUploader_image_upload");$container.trigger({type:"AttachmentUploaded",ajaxData:c})}};XenForo.AttachmentUploader=function(c){var d=a(c.data("trigger"));c.closest("form");var b={},h=function(a,b,h){(b=c.data("err-"+b)||h)||(b=c.data("err-unknown"));a?XenForo.alert(b+
"<br /><br />"+XenForo.htmlspecialchars(a.name)):XenForo.alert(b)},t=c.data("maxfilesize");c.data("maxuploads");var f=c.data("extensions"),r=c.data("uniquekey");f=f.replace(/[;*.]/g,"").replace(/,{2,}/g,",").replace(/^,+/,"").replace(/,+$/,"");this.uniqueKey=r;c.show();var n=l.Flow?!0:!1,q=navigator.userAgent;q.match(/Android [1-4]/)&&(q=q.match(/Chrome\/([0-9]+)/),!q||33>parseInt(q[1],10))&&(console.log("Old Android WebView detected. Must fallback to basic uploader."),n=!1);if(n){var g=!1;n={target:c.data("action"),
allowDuplicateUploads:!0,fileParameterName:c.data("postname"),query:function(){var h=a.extend({_xfToken:XenForo._csrfToken,_xfNoRedirect:1,_xfResponseType:g?"json-text":"json"},b);c.find(".HiddenInput").each(function(c,b){c=a(b);h[c.data("name")]=c.data("value")});return h},simultaneousUploads:1,testChunks:!1,chunkSize:4294967296};var k=new Flow(n);k.support||(k=new FustyFlow(n),g=!0);n=a("<span />").insertAfter(d).append(d);k.assignBrowse(n[0],!1,!1,{accept:"."+f.toLowerCase().replace(/,/g,",.")});
g&&(f=d.outerWidth(),30<f&&n.css("width",f));d.on("click BeforeOverlayTrigger",function(a){a.preventDefault()});k.on("fileAdded",function(b){var f=!1;b.id=b.uniqueIdentifier;switch(b.name.substr(b.name.lastIndexOf(".")).toLowerCase()){case ".jpg":case ".jpeg":case ".jpe":case ".png":case ".gif":f=!0}var d=a.Event("AttachmentQueueValidation");d.file=b;d.flow=k;d.isImage=f;c.trigger(d);if(d.isDefaultPrevented())return!1;if(0<t&&b.size>t&&!f)return h(b,110),!1;d=a.Event("AttachmentQueued");d.file=b;
d.flow=k;d.isImage=f;c.trigger(d)});k.on("filesSubmitted",function(){k.upload()});k.on("fileProgress",function(a){a.id=a.uniqueIdentifier;c.trigger({type:"AttachmentUploadProgress",file:a,bytes:Math.round(a.progress()*a.size),flow:k})});k.on("fileSuccess",function(b,h){try{g&&"<"==h.substr(0,1)&&(h=a(a.parseHTML(h)).text());var d=a.parseJSON(h)}catch(u){console.warn(u);return}b.id=b.uniqueIdentifier;d.error?c.trigger({type:"AttachmentUploadError",file:b,ajaxData:d,flow:k}):c.trigger({type:"AttachmentUploaded",
file:b,ajaxData:d,flow:k})});k.on("fileError",function(a,b){a.id=a.uniqueIdentifier;c.trigger({type:"AttachmentUploadError",file:a,errorCode:0,message:b,ajaxData:{error:[c.data("err-unknown")]},flow:k})})}else console.error("flow.js must be loaded");a(e).bind("AutoInlineUploadComplete",function(b){if(r&&b.ajaxData&&r!==b.ajaxData.key)return!1;if(a(b.target).is("form.AttachmentUploadForm"))return d.overlay()&&d.overlay().close(),c.trigger({type:"AttachmentUploaded",ajaxData:b.ajaxData}),!1});return{getSwfUploader:function(){return null},
getFlowUploader:function(){return k},swfAlert:h,attachmentErrorAlert:h}};XenForo.AttachmentEditor=function(c){this.setVisibility=function(a){var b=c.closest(".ctrlUnit"),d=c.find(".AttachmentInsertAllBlock"),f=c.find(".AttachedFile:not(#AttachedFileTemplate)"),g=f.parents(".AttachedFilesUnit").find(".ctrlUnit.submitUnit .button"),n=f.filter(".Processing"),e=f.filter(".AttachedImage");console.log("Attachments changed, total files: %d, images: %d",f.length,e.length);0==b.length&&(b=c);!0===a?f.length?
(1<e.length?d.show():d.hide(),b.show()):b.hide():f.length?(1<e.length?b.is(":hidden")?d.show():d.xfFadeDown(XenForo.speed.fast):b.is(":hidden")?d.hide():d.xfFadeUp(XenForo.speed.fast,!1,XenForo.speed.fast,"swing"),b.xfFadeDown(XenForo.speed.normal)):(d.slideUp(XenForo.speed.fast),b.xfFadeUp(XenForo.speed.normal,!1,!1,"swing"));n.length||g.prop("disabled",!1).removeClass("disabled")};this.setVisibility(!0);a("#AttachmentUploader_"+c.data("uploadtype")).bind({AttachmentQueued:function(b){console.info("Queued file %s (%d bytes).",
b.file.name,b.file.size);var d=a("#AttachedFileTemplate").clone().attr("id",b.file.id);d.find(".Filename").text(b.file.name);d.find(".ProgressCounter").text("0%");d.find(".ProgressGraphic span").css("width","0%");b.isImage&&d.addClass("AttachedImage");d.xfInsert("prependTo",".AttachmentList_"+c.data("uploadtype")+".New",null,g);d.find(".AttachmentCanceller").css("display","block").click(function(){b.swfUpload?b.swfUpload.cancelUpload(b.file.id):b.file.flowObj&&b.file.cancel();d.xfRemove(null,function(){c.trigger("AttachmentsChanged")},
p,"swing")});d.parents(".AttachedFilesUnit").find(".submitUnit .button").prop("disabled",!0).addClass("disabled");c.trigger("AttachmentsChanged")},AttachmentUploadProgress:function(b){console.log("Uploaded %d/%d bytes.",b.bytes,b.file.size);var c=Math.min(100,Math.ceil(100*b.bytes/b.file.size)),d=c+"%";b=a("#"+b.file.id);var f=b.find(".ProgressCounter"),g=b.find(".ProgressGraphic");f.text(d);g.css("width",d);100<=c&&b.find(".AttachmentCanceller").prop("disabled",!0).addClass("disabled");g.width()>
f.outerWidth()&&f.appendTo(g)},AttachmentUploadError:function(b){var c="",d=b.file,f=d.uniqueIdentifier||d.id;a.each(b.ajaxData.error,function(a,b){c+=b+"\n"});XenForo.alert(c+"<br /><br />"+XenForo.htmlspecialchars(d.name));d=a("#"+f);var g=d.closest(".AttachmentEditor");d.xfRemove(null,function(){g.trigger("AttachmentsChanged")},p,"swing");console.warn("AttachmentUploadError: %o",b)},AttachmentUploaded:function(b){if(b.file){var d=b.file,e=a("#"+(d.uniqueIdentifier||d.id)),f=e.find(".AttachmentText"),
l=e.find(".Thumbnail");new XenForo.ExtLoader(b.ajaxData,function(){f.fadeOut(XenForo.speed.fast,function(){var c=a(b.ajaxData.templateHtml).find(".AttachmentText");c.xfInsert("insertBefore",f,"fadeIn",XenForo.speed.fast);a(b.ajaxData.templateHtml).find(".Thumbnail").xfInsert("replaceAll",l,null,g);f.xfRemove();c.find(".itemExtraInput.itemInputs").data("expanded")&&c.find("a.ToggleTrigger.ItemToggleTrigger").click();e.attr("id","attachment"+b.ajaxData.attachment_id)})})}else e=a("#attachment"+b.ajaxData.attachment_id),
e.length||new XenForo.ExtLoader(b.ajaxData,function(){var d=a(b.ajaxData.templateHtml),f=d.find(".AttachmentText");d.xfInsert("prependTo",c.find(".AttachmentList_"+c.data("uploadtype")+".New"),null,g);f.find(".itemExtraInput.itemInputs").data("expanded")&&f.find("a.ToggleTrigger.ItemToggleTrigger").click()});e.removeClass("Processing");c.trigger("AttachmentsChanged")}});var d=a.context(this,"setVisibility");a("#QuickReply").bind("QuickReplyComplete",function(a){c.find(".AttachmentList.New li:not(#AttachedFileTemplate)").xfRemove(null,
d)});c.bind("AttachmentsChanged",d)};XenForo.AttachmentDeleter=function(c){c.css("display","inline-block").click(function(c){var b=a(c.target),d=b.attr("href")||b.data("href"),e=b.closest(".AttachedFile");c=b.closest(".AttachedFile").find(".Thumbnail a").data("attachmentid");if(d)return e.xfFadeUp(XenForo.speed.normal,null,p,"swing"),XenForo.ajax(d,"",function(a,b){if(XenForo.hasResponseError(a))return e.xfFadeDown(XenForo.speed.normal),!1;var c=e.closest(".AttachmentEditor");e.xfRemove(null,function(){c.trigger("AttachmentsChanged")},
p,"swing")}),c&&(b=XenForo.getEditorInForm(b.closest("form"),":not(.NoAttachment)"))&&b.$editor&&(b.$editor.find("img[alt=attachFull"+c+"], img[alt=attachThumb"+c+"]").remove(),(c=b.$editor.data("xenForoElastic"))&&c()),!1;console.warn("Unable to locate href for attachment deletion from %o",b)})};XenForo.register(".AttachmentDownloader","XenForo.AttachmentDownloader");XenForo.register(".AttachmentUploader","XenForo.AttachmentUploader");XenForo.register(".AttachmentEditor","XenForo.AttachmentEditor");
XenForo.register(".AttachmentDeleter","XenForo.AttachmentDeleter");XenForo.register(".SetAllTitlesOverlay","XenForo.SetAllTitlesForm");XenForo.register(".InsertFilename","XenForo.MediaGallery.InsertFilename");XenForo.register("a.SetAllImageTitles","XenForo.MediaGallery.SetAllImageTitles");XenForo.register("a.SetAllImageDescriptions","XenForo.MediaGallery.SetAllImageDescriptions");XenForo.register("a.SetAllVideoTitles","XenForo.MediaGallery.SetAllVideoTitles");XenForo.register("a.SetAllVideoDescriptions",
"XenForo.MediaGallery.SetAllVideoDescriptions")}(jQuery,this,document);
