/*
 * XenForo media_upload.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,l,h){a instanceof String&&(a=String(a));for(var k=a.length,g=0;g<k;g++){var m=a[g];if(l.call(h,m,g,a))return{i:g,v:m}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,l,h){a!=Array.prototype&&a!=Object.prototype&&(a[l]=h.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,l,h,k){if(l){h=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var g=a[k];g in h||(h[g]={});h=h[g]}a=a[a.length-1];k=h[a];l=l(k);l!=k&&null!=l&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,h){return $jscomp.findInternal(this,a,h).v}},"es6","es3");
!function(a,l,h,k){XenForo.MediaGallery={SetAllImageTitles:function(c){c.click(function(){$titles=a("#SetAllImageTitleText").val();a("#SetAllImageTitleText").val("");$titles&&a(".SetImageTitle").each(function(c,b){b=a(b);var f=$titles;f=f.replace("%f",b.data("filename"));f=f.replace("%n",c+1);a(this).val(f)})})},SetAllImageDescriptions:function(c){c.click(function(){this.titles=a("#SetAllImageDescriptionText").val();a("#SetAllImageDescriptionText").val("");this.titles&&a(".SetImageDescription").val(this.titles)})},
SetAllVideoTitles:function(c){c.click(function(){this.titles=a("#SetAllVideoTitleText").val();a("#SetAllVideoTitleText").val("");this.titles&&a(".SetVideoTitle").val(this.titles)})},SetAllVideoDescriptions:function(c){c.click(function(){this.titles=a("#SetAllVideoDescriptionText").val();a("#SetAllVideoDescriptionText").val("");this.titles&&a(".SetVideoDescription").val(this.titles)})},InsertFilename:function(c){c.click(function(d){d.preventDefault();d=c.data("filename");var b=c.data("target");a(b).val(d)})}};
XenForo.SetAllTitlesForm=function(a){a.closest("form").submit(function(a){a.preventDefault();return!1});a.overlay().close()};var g=XenForo.speed.normal,m=XenForo.speed.fast;XenForo.AttachmentDownloader=function(a){this.__construct(a)};XenForo.AttachmentDownloader.prototype={__construct:function(c){this.$input=c;this.url=c.data("href");this.uniqueKey=c.data("key");a(".DownloadTrigger").bind({click:a.context(this,"doDownload")})},doDownload:function(c){c.preventDefault();this.xhr=XenForo.ajax(this.url,
{image_url:this.$input.val()},a.context(this,"ajaxSuccess"),{error:"failure"});this.$input.val("")},ajaxSuccess:function(c){if(c.error){var d="";a.each(c.error,function(a,c){d+=c+"\n"});XenForo.alert(d);return!1}$container=a("#AttachmentUploader_image_upload");$container.trigger({type:"AttachmentUploaded",ajaxData:c})}};XenForo.AttachmentUploader=function(c){var d=a(c.data("trigger"));c.closest("form");var b=a(c.data("placeholder")),f={},e=null,p=null,n=c.data("maxfilesize");c.data("maxuploads");
var g=c.data("extensions"),k=c.data("uniquekey");this.uniqueKey=k;c.show();var m=XenForo.canonicalizeUrl(c.data("flashurl")||"js/swfupload/Flash/swfupload.swf");console.info("flash url: %s",m);"function"!=typeof SWFUpload||l.navigator.userAgent.match(/Android|iOS|iPhone|iPad|Mobile Safari|Trident\/7.0/i)||(e=new SWFUpload({upload_url:c.data("action"),file_post_name:c.data("postname"),file_types:"*."+(g.toLowerCase()+","+g.toUpperCase()).replace(/,/g,";*."),post_params:a.extend({_xfToken:XenForo._csrfToken,
_xfNoRedirect:1,_xfResponseType:"json"},f),button_placeholder_id:b.attr("id"),button_width:1,button_height:1,button_window_mode:SWFUpload.WINDOW_MODE.TRANSPARENT,button_cursor:SWFUpload.CURSOR.HAND,flash_url:m,prevent_swf_caching:!1,swfupload_loaded_handler:function(){this.setButtonDimensions(d.outerWidth(),d.outerHeight());c.find(".HiddenInput").each(function(c,b){e.addPostParam(a(b).data("name"),a(b).data("value"))});a(h).bind("CSRFRefresh",function(a){a.ajaxData&&(e.addPostParam("_xfToken",a.ajaxData.csrfToken),
e.addPostParam("_xfSessionId",a.ajaxData.sessionId))})},file_dialog_complete_handler:function(a,c){try{0<this.getStats().files_queued&&this.startUpload(this.getFile(0).ID)}catch(r){this.debug(r)}},file_queued_handler:function(b){switch(b.name.substr(b.name.lastIndexOf(".")).toLowerCase()){case ".jpg":case ".jpeg":case ".jpe":case ".png":case ".gif":var f=!0;break;default:f=!1}var e=a.Event("AttachmentQueueValidation");e.file=b;e.swfUpload=this;e.isImage=f;c.trigger(e);e.isDefaultPrevented()||(0<n&&
b.size>n&&!f?(this.cancelUpload(b.id,!1),"function"==typeof this.settings.file_queue_error_handler&&this.settings.file_queue_error_handler.call(this,b,SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT,"The uploaded file is too large.")):(e=a.Event("AttachmentQueued"),e.file=b,e.swfUpload=this,e.isImage=f,c.trigger(e)))},file_queue_error_handler:function(b,f,e){var d=a.Event("AttachmentQueueError");d.file=b;d.errorCode=f;d.message=e;d.swfUpload=this;c.trigger(d);d.isDefaultPrevented()||p(b,f,e)},upload_start_handler:function(a){console.log("Uploading %s",
a.name)},upload_progress_handler:function(a,b){c.trigger({type:"AttachmentUploadProgress",file:a,bytes:b,swfUpload:this})},upload_success_handler:function(b,f,e){try{var d=a.parseJSON(f)}catch(t){console.warn(t);return}d.error?c.trigger({type:"AttachmentUploadError",file:b,ajaxData:d,swfUpload:this}):c.trigger({type:"AttachmentUploaded",file:b,ajaxData:d,swfUpload:this})},upload_error_handler:function(a,b,f){b!=SWFUpload.UPLOAD_ERROR.FILE_CANCELLED&&(console.warn("Upload failed: %o",arguments),c.trigger({type:"AttachmentUploadError",
file:a,errorCode:b,message:f,ajaxData:{error:[c.data("err-unknown")]},swfUpload:this}))},upload_complete_handler:function(a){try{0<this.getStats().files_queued?this.startUpload(this.getFile(0).ID):console.info("All files uploaded.")}catch(q){this.debug(q)}}}),p=function(a,b,f){b=c.data("err"+b)||f;a?XenForo.alert(b+"<br /><br />"+XenForo.htmlspecialchars(a.name)):XenForo.alert(b)});a(h).bind("AutoInlineUploadComplete",function(b){if(k&&b.ajaxData&&k!==b.ajaxData.key)return!1;if(a(b.target).is("form.AttachmentUploadForm"))return d.overlay()&&
d.overlay().close(),c.trigger({type:"AttachmentUploaded",ajaxData:b.ajaxData}),!1});return{getSwfUploader:function(){return e},swfAlert:p}};XenForo.AttachmentEditor=function(c){this.setVisibility=function(a){var b=c.closest(".ctrlUnit"),e=c.find(".AttachmentInsertAllBlock"),d=c.find(".AttachedFile:not(#AttachedFileTemplate)"),n=d.parents(".AttachedFilesUnit").find(".ctrlUnit.submitUnit .button"),h=d.filter(".Processing"),g=d.filter(".AttachedImage");console.log("Attachments changed, total files: %d, images: %d",
d.length,g.length);0==b.length&&(b=c);!0===a?d.length?(1<g.length?e.show():e.hide(),b.show()):b.hide():d.length?(1<g.length?b.is(":hidden")?e.show():e.xfFadeDown(XenForo.speed.fast):b.is(":hidden")?e.hide():e.xfFadeUp(XenForo.speed.fast,!1,XenForo.speed.fast,"swing"),b.xfFadeDown(XenForo.speed.normal)):(e.slideUp(XenForo.speed.fast),b.xfFadeUp(XenForo.speed.normal,!1,!1,"swing"));h.length||n.prop("disabled",!1).removeClass("disabled")};this.setVisibility(!0);a("#AttachmentUploader_"+c.data("uploadtype")).bind({AttachmentQueued:function(b){console.info("Queued file %s (%d bytes).",
b.file.name,b.file.size);var f=a("#AttachedFileTemplate").clone().attr("id",b.file.id);f.find(".Filename").text(b.file.name);f.find(".ProgressCounter").text("0%");f.find(".ProgressGraphic span").css("width","0%");b.isImage&&f.addClass("AttachedImage");f.xfInsert("prependTo",".AttachmentList_"+c.data("uploadtype")+".New",null,g);f.find(".AttachmentCanceller").css("display","block").click(function(){b.swfUpload.cancelUpload(b.file.id);f.xfRemove(null,function(){c.trigger("AttachmentsChanged")},m,"swing")});
f.parents(".AttachedFilesUnit").find(".submitUnit .button").prop("disabled",!0).addClass("disabled");c.trigger("AttachmentsChanged")},AttachmentUploadProgress:function(b){console.log("Uploaded %d/%d bytes.",b.bytes,b.file.size);var c=Math.min(100,Math.ceil(100*b.bytes/b.file.size)),e=c+"%";b=a("#"+b.file.id);var d=b.find(".ProgressCounter"),g=b.find(".ProgressGraphic");d.text(e);g.css("width",e);100<=c&&b.find(".AttachmentCanceller").prop("disabled",!0).addClass("disabled");g.width()>d.outerWidth()&&
d.appendTo(g)},AttachmentUploadError:function(b){var c="";a.each(b.ajaxData.error,function(a,b){c+=b+"\n"});XenForo.alert(c+"<br /><br />"+XenForo.htmlspecialchars(b.file.name));var d=a("#"+b.file.id),g=d.closest(".AttachmentEditor");d.xfRemove(null,function(){g.trigger("AttachmentsChanged")},m,"swing");console.warn("AttachmentUploadError: %o",b)},AttachmentUploaded:function(b){if(b.file){var d=a("#"+b.file.id),e=d.find(".AttachmentText"),h=d.find(".Thumbnail");new XenForo.ExtLoader(b.ajaxData,function(){e.fadeOut(XenForo.speed.fast,
function(){var c=a(b.ajaxData.templateHtml).find(".AttachmentText");c.xfInsert("insertBefore",e,"fadeIn",XenForo.speed.fast);a(b.ajaxData.templateHtml).find(".Thumbnail").xfInsert("replaceAll",h,null,g);e.xfRemove();c.find(".itemExtraInput.itemInputs").data("expanded")&&c.find("a.ToggleTrigger.ItemToggleTrigger").click();d.attr("id","attachment"+b.ajaxData.attachment_id)})})}else d=a("#attachment"+b.ajaxData.attachment_id),d.length||new XenForo.ExtLoader(b.ajaxData,function(){var d=a(b.ajaxData.templateHtml),
e=d.find(".AttachmentText");d.xfInsert("prependTo",c.find(".AttachmentList_"+c.data("uploadtype")+".New"),null,g);e.find(".itemExtraInput.itemInputs").data("expanded")&&e.find("a.ToggleTrigger.ItemToggleTrigger").click()});d.removeClass("Processing");c.trigger("AttachmentsChanged")}});var d=a.context(this,"setVisibility");a("#QuickReply").bind("QuickReplyComplete",function(a){c.find(".AttachmentList.New li:not(#AttachedFileTemplate)").xfRemove(null,d)});c.bind("AttachmentsChanged",d)};XenForo.AttachmentDeleter=
function(c){c.css("display","inline-block").click(function(c){var b=a(c.target),d=b.attr("href")||b.data("href"),e=b.closest(".AttachedFile");c=b.closest(".AttachedFile").find(".Thumbnail a").data("attachmentid");if(d)return e.xfFadeUp(XenForo.speed.normal,null,m,"swing"),XenForo.ajax(d,"",function(a,b){if(XenForo.hasResponseError(a))return e.xfFadeDown(XenForo.speed.normal),!1;var c=e.closest(".AttachmentEditor");e.xfRemove(null,function(){c.trigger("AttachmentsChanged")},m,"swing")}),c&&(b=XenForo.getEditorInForm(b.closest("form"),
":not(.NoAttachment)"))&&b.$editor&&(b.$editor.find("img[alt=attachFull"+c+"], img[alt=attachThumb"+c+"]").remove(),(c=b.$editor.data("xenForoElastic"))&&c()),!1;console.warn("Unable to locate href for attachment deletion from %o",b)})};XenForo.register(".AttachmentDownloader","XenForo.AttachmentDownloader");XenForo.register(".AttachmentUploader","XenForo.AttachmentUploader");XenForo.register(".AttachmentEditor","XenForo.AttachmentEditor");XenForo.register(".AttachmentDeleter","XenForo.AttachmentDeleter");
XenForo.register(".SetAllTitlesOverlay","XenForo.SetAllTitlesForm");XenForo.register(".InsertFilename","XenForo.MediaGallery.InsertFilename");XenForo.register("a.SetAllImageTitles","XenForo.MediaGallery.SetAllImageTitles");XenForo.register("a.SetAllImageDescriptions","XenForo.MediaGallery.SetAllImageDescriptions");XenForo.register("a.SetAllVideoTitles","XenForo.MediaGallery.SetAllVideoTitles");XenForo.register("a.SetAllVideoDescriptions","XenForo.MediaGallery.SetAllVideoDescriptions")}(jQuery,this,
document);
