/*
 * XenForo media_slider.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,f,h){c instanceof String&&(c=String(c));for(var l=c.length,a=0;a<l;a++){var b=c[a];if(f.call(h,b,a,c))return{i:a,v:b}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,f,h){c!=Array.prototype&&c!=Object.prototype&&(c[f]=h.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,f,h,l){if(f){h=$jscomp.global;c=c.split(".");for(l=0;l<c.length-1;l++){var a=c[l];a in h||(h[a]={});h=h[a]}c=c[c.length-1];l=h[c];f=f(l);f!=l&&null!=f&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,h){return $jscomp.findInternal(this,c,h).v}},"es6","es3");
!function(c,f,h,l){XenForo.XenGalleryCarousel=function(a){this.__construct(a)};XenForo.XenGalleryCarousel.prototype={__construct:function(a){if(!(c.browser.msie&&9>parseInt(c.browser.version,10))){var b=a.data("target");this.target=c(b);var g=this.target.data("responsive")?!0:!1;this.responsive=g;this.slideWidth=this.target.data("slide-width")?this.target.data("slide-width"):160;this.windowWidth=c(f).width();this.windowHeight=c(f).height();var e=this.getWidthBasedMaxSlides(),d=this.target.data("navigation")?
!0:!1;e=this.target.data("items")?a.data("items"):e;var k=this.target.data("responsive-wide")?c.parseJSON("["+a.data("responsive-wide")+"]"):[800,2],p=this.target.data("responsive-medium")?c.parseJSON("["+a.data("responsive-medium")+"]"):[600,2],h=this.target.data("responsive-narrow")?c.parseJSON("["+a.data("responsive-narrow")+"]"):[400,2],l=this.target.data("direction")?this.target.data("direction"):"ltr",m=this.target.data("nav-next"),n=this.target.data("nav-prev");this.window=c(f);"undefined"==
typeof n&&(n='<i class="fa fa-chevron-left fa-3x"></i>');"undefined"==typeof m&&(m='<i class="fa fa-chevron-right fa-3x"></i>');"rtl"==l&&($switchprev=m,$switchnext=n,n=$switchprev,m=$switchnext);c(".thumbContainer").hover(function(){c(this).addClass("showOverlay")},function(){c(this).removeClass("showOverlay")});this.target.length?(this.target.owlCarousel({direction:l,items:e,itemsDesktopSmall:k,itemsTablet:p,itemsTabletSmall:!1,itemsMobile:h,lazyLoad:!0,pagination:!1,navigation:d,navigationText:[n,
m],slideSpeed:300,responsive:g,afterInit:function(){this.target=c(b);this.target.find(".thumbImage").first().bind("load",function(){var a=c(this),d=c(b),e=a.height(),g=d.find(".owl-prev");d=d.find(".owl-next");e=Math.floor((e-45)/2);g.css({top:e});d.css({top:e});g.show();d.show();this.complete||a.trigger("load")});a.parents(".xmgCarouselContainer").xfFadeIn();this.target.xfSlideDown()},afterUpdate:function(){var a=c(b),d=a.find(".thumbImage").first().height(),e=a.find(".owl-prev");a=a.find(".owl-next");
d=Math.floor((d-45)/2);e.css({top:d});a.css({top:d});e.show();a.show()}}),this.owl=this.target.data("owlCarousel"),this.window.bind({resize:c.context(this,"triggerResize")})):a.hide()}},triggerResize:function(){if(this.responsive){var a=c(f).width(),b=c(f).height();a!=this.windowWidth&&b!=this.windowHeight&&(a=this.getWidthBasedMaxSlides(),this.owl.reinit({items:a}))}},getWidthBasedMaxSlides:function(a){a=c(".mainContent").width();if(this.responsive)return Math.floor(a/this.slideWidth)}};XenForo.register(".XmgCarousel",
"XenForo.XenGalleryCarousel")}(jQuery,this,document);"function"!==typeof Object.create&&(Object.create=function(c){function f(){}f.prototype=c;return new f});
(function(c,f,h){var l={init:function(a,b){this.$elem=c(b);this.options=c.extend({},c.fn.owlCarousel.options,this.$elem.data(),a);this.userOptions=a;this.loadContent()},loadContent:function(){function a(a){var d,c="";if("function"===typeof b.options.jsonSuccess)b.options.jsonSuccess.apply(this,[a]);else{for(d in a.owl)a.owl.hasOwnProperty(d)&&(c+=a.owl[d].item);b.$elem.html(c)}b.logIn()}var b=this;"function"===typeof b.options.beforeInit&&b.options.beforeInit.apply(this,[b.$elem]);if("string"===typeof b.options.jsonPath){var g=
b.options.jsonPath;c.getJSON(g,a)}else b.logIn()},logIn:function(){this.$elem.data("owl-originalStyles",this.$elem.attr("style")).data("owl-originalClasses",this.$elem.attr("class"));this.$elem.css({opacity:0});this.orignalItems=this.options.items;this.checkBrowser();this.wrapperWidth=0;this.checkVisible=null;this.setVars()},setVars:function(){if(0===this.$elem.children().length)return!1;this.baseClass();this.eventTypes();this.$userItems=this.$elem.children();this.itemsAmount=this.$userItems.length;
this.wrapItems();this.$owlItems=this.$elem.find(".owl-item");this.$owlWrapper=this.$elem.find(".owl-wrapper");this.playDirection="next";this.prevItem=0;this.prevArr=[0];this.currentItem=0;this.customEvents();this.onStartup()},onStartup:function(){this.updateItems();this.calculateAll();this.buildControls();this.updateControls();this.response();this.moveEvents();this.stopOnHover();this.owlStatus();!1!==this.options.transitionStyle&&this.transitionTypes(this.options.transitionStyle);!0===this.options.autoPlay&&
(this.options.autoPlay=5E3);this.play();this.$elem.find(".owl-wrapper").css("display","block");this.$elem.is(":visible")?this.$elem.css("opacity",1):this.watchVisibility();this.onstartup=!1;this.eachMoveUpdate();"function"===typeof this.options.afterInit&&this.options.afterInit.apply(this,[this.$elem])},eachMoveUpdate:function(){!0===this.options.lazyLoad&&this.lazyLoad();!0===this.options.autoHeight&&this.autoHeight();this.onVisibleItems();"function"===typeof this.options.afterAction&&this.options.afterAction.apply(this,
[this.$elem])},updateVars:function(){"function"===typeof this.options.beforeUpdate&&this.options.beforeUpdate.apply(this,[this.$elem]);this.watchVisibility();this.updateItems();this.calculateAll();this.updatePosition();this.updateControls();this.eachMoveUpdate();"function"===typeof this.options.afterUpdate&&this.options.afterUpdate.apply(this,[this.$elem])},reload:function(){var a=this;f.setTimeout(function(){a.updateVars()},0)},watchVisibility:function(){var a=this;if(!1===a.$elem.is(":visible"))a.$elem.css({opacity:0}),
f.clearInterval(a.autoPlayInterval),f.clearInterval(a.checkVisible);else return!1;a.checkVisible=f.setInterval(function(){a.$elem.is(":visible")&&(a.reload(),a.$elem.animate({opacity:1},200),f.clearInterval(a.checkVisible))},500)},wrapItems:function(){this.$userItems.wrapAll('<div class="owl-wrapper">').wrap('<div class="owl-item"></div>');this.$elem.find(".owl-wrapper").wrap('<div class="owl-wrapper-outer">');this.wrapperOuter=this.$elem.find(".owl-wrapper-outer");this.$elem.css("display","block")},
baseClass:function(){var a=this.$elem.hasClass(this.options.baseClass),b=this.$elem.hasClass(this.options.theme);a||this.$elem.addClass(this.options.baseClass);b||this.$elem.addClass(this.options.theme)},updateItems:function(){var a;if(!1===this.options.responsive)return!1;if(!0===this.options.singleItem)return this.options.items=this.orignalItems=1,this.options.itemsCustom=!1,this.options.itemsDesktop=!1,this.options.itemsDesktopSmall=!1,this.options.itemsTablet=!1,this.options.itemsTabletSmall=
!1,this.options.itemsMobile=!1;var b=c(this.options.responsiveBaseWidth).width();b>(this.options.itemsDesktop[0]||this.orignalItems)&&(this.options.items=this.orignalItems);if(!1!==this.options.itemsCustom)for(this.options.itemsCustom.sort(function(a,b){return a[0]-b[0]}),a=0;a<this.options.itemsCustom.length;a+=1)this.options.itemsCustom[a][0]<=b&&(this.options.items=this.options.itemsCustom[a][1]);else b<=this.options.itemsDesktop[0]&&!1!==this.options.itemsDesktop&&(this.options.items=this.options.itemsDesktop[1]),
b<=this.options.itemsDesktopSmall[0]&&!1!==this.options.itemsDesktopSmall&&(this.options.items=this.options.itemsDesktopSmall[1]),b<=this.options.itemsTablet[0]&&!1!==this.options.itemsTablet&&(this.options.items=this.options.itemsTablet[1]),b<=this.options.itemsTabletSmall[0]&&!1!==this.options.itemsTabletSmall&&(this.options.items=this.options.itemsTabletSmall[1]),b<=this.options.itemsMobile[0]&&!1!==this.options.itemsMobile&&(this.options.items=this.options.itemsMobile[1]);this.options.items>this.itemsAmount&&
!0===this.options.itemsScaleUp&&(this.options.items=this.itemsAmount)},response:function(){var a=this,b;if(!0!==a.options.responsive)return!1;var g=c(f).width();a.resizer=function(){c(f).width()!==g&&(!1!==a.options.autoPlay&&f.clearInterval(a.autoPlayInterval),f.clearTimeout(b),b=f.setTimeout(function(){g=c(f).width();a.updateVars()},a.options.responsiveRefreshRate))};c(f).resize(a.resizer)},updatePosition:function(){this.jumpTo(this.currentItem);!1!==this.options.autoPlay&&this.checkAp()},appendItemsSizes:function(){var a=
this,b=0,g=a.itemsAmount-a.options.items;a.$owlItems.each(function(e){var d=c(this);d.css({width:a.itemWidth}).data("owl-item",Number(e));if(0===e%a.options.items||e===g)e>g||(b+=1);d.data("owl-roundPages",b)})},appendWrapperSizes:function(){var a=this.$owlItems.length*this.itemWidth,b;"rtl"==this.options.direction?b={right:0,direction:"rtl"}:b={left:0};this.$owlWrapper.css({width:2*a});this.$owlWrapper.css(b);this.appendItemsSizes()},calculateAll:function(){this.calculateWidth();this.appendWrapperSizes();
this.loops();this.max()},calculateWidth:function(){this.itemWidth=Math.round(this.$elem.width()/this.options.items)},max:function(){var a=-1*(this.itemsAmount*this.itemWidth-this.options.items*this.itemWidth);this.options.items>this.itemsAmount?this.maximumPixels=a=this.maximumItem=0:(this.maximumItem=this.itemsAmount-this.options.items,this.maximumPixels=a);return a},min:function(){return 0},loops:function(){var a=0,b=0,g;this.positionsInArray=[0];this.pagesInArray=[];for(g=0;g<this.itemsAmount;g+=
1)if(b+=this.itemWidth,this.positionsInArray.push(-b),!0===this.options.scrollPerPage){var e=c(this.$owlItems[g]);e=e.data("owl-roundPages");e!==a&&(this.pagesInArray[a]=this.positionsInArray[g],a=e)}},buildControls:function(){if(!0===this.options.navigation||!0===this.options.pagination)this.owlControls=c('<div class="owl-controls"/>').toggleClass("clickable",!this.browser.isTouch).appendTo(this.$elem);!0===this.options.pagination&&this.buildPagination();!0===this.options.navigation&&this.buildButtons()},
buildButtons:function(){var a=this,b=c('<div class="owl-buttons"/>');a.owlControls.append(b);a.buttonPrev=c("<div/>",{"class":"owl-prev",html:a.options.navigationText[0]||""});a.buttonNext=c("<div/>",{"class":"owl-next",html:a.options.navigationText[1]||""});b.append(a.buttonPrev).append(a.buttonNext);b.on("touchstart.owlControls mousedown.owlControls",'div[class^="owl"]',function(a){a.preventDefault()});b.on("touchend.owlControls mouseup.owlControls",'div[class^="owl"]',function(b){b.preventDefault();
c(this).hasClass("owl-next")?a.next():a.prev()})},buildPagination:function(){var a=this;a.paginationWrapper=c('<div class="owl-pagination"/>');a.owlControls.append(a.paginationWrapper);a.paginationWrapper.on("touchend.owlControls mouseup.owlControls",".owl-page",function(b){b.preventDefault();Number(c(this).data("owl-page"))!==a.currentItem&&a.goTo(Number(c(this).data("owl-page")),!0)})},updatePagination:function(){var a,b;if(!1===this.options.pagination)return!1;this.paginationWrapper.html("");var g=
0;var e=this.itemsAmount-this.itemsAmount%this.options.items;for(b=0;b<this.itemsAmount;b+=1)if(0===b%this.options.items){g+=1;e===b&&(a=this.itemsAmount-this.options.items);var d=c("<div/>",{"class":"owl-page"});var f=c("<span></span>",{text:!0===this.options.paginationNumbers?g:"","class":!0===this.options.paginationNumbers?"owl-numbers":""});d.append(f);d.data("owl-page",e===b?a:b);d.data("owl-roundPages",g);this.paginationWrapper.append(d)}this.checkPagination()},checkPagination:function(){var a=
this;if(!1===a.options.pagination)return!1;a.paginationWrapper.find(".owl-page").each(function(){c(this).data("owl-roundPages")===c(a.$owlItems[a.currentItem]).data("owl-roundPages")&&(a.paginationWrapper.find(".owl-page").removeClass("active"),c(this).addClass("active"))})},checkNavigation:function(){if(!1===this.options.navigation)return!1;!1===this.options.rewindNav&&(0===this.currentItem&&0===this.maximumItem?(this.buttonPrev.addClass("disabled"),this.buttonNext.addClass("disabled")):0===this.currentItem&&
0!==this.maximumItem?(this.buttonPrev.addClass("disabled"),this.buttonNext.removeClass("disabled")):this.currentItem===this.maximumItem?(this.buttonPrev.removeClass("disabled"),this.buttonNext.addClass("disabled")):0!==this.currentItem&&this.currentItem!==this.maximumItem&&(this.buttonPrev.removeClass("disabled"),this.buttonNext.removeClass("disabled")))},updateControls:function(){this.updatePagination();this.checkNavigation();this.owlControls&&(this.options.items>=this.itemsAmount?this.owlControls.hide():
this.owlControls.show())},destroyControls:function(){this.owlControls&&this.owlControls.remove()},next:function(a){if(this.isTransition)return!1;this.currentItem+=!0===this.options.scrollPerPage?this.options.items:1;if(this.currentItem>this.maximumItem+(!0===this.options.scrollPerPage?this.options.items-1:0))if(!0===this.options.rewindNav)this.currentItem=0,a="rewind";else return this.currentItem=this.maximumItem,!1;this.goTo(this.currentItem,a)},prev:function(a){if(this.isTransition)return!1;this.currentItem=
!0===this.options.scrollPerPage&&0<this.currentItem&&this.currentItem<this.options.items?0:this.currentItem-(!0===this.options.scrollPerPage?this.options.items:1);if(0>this.currentItem)if(!0===this.options.rewindNav)this.currentItem=this.maximumItem,a="rewind";else return this.currentItem=0,!1;this.goTo(this.currentItem,a)},goTo:function(a,b,c){var e=this;if(e.isTransition)return!1;"function"===typeof e.options.beforeMove&&e.options.beforeMove.apply(this,[e.$elem]);a>=e.maximumItem?a=e.maximumItem:
0>=a&&(a=0);e.currentItem=e.owl.currentItem=a;if(!1!==e.options.transitionStyle&&"drag"!==c&&1===e.options.items&&!0===e.browser.support3d)return e.swapSpeed(0),!0===e.browser.support3d?e.transition3d(e.positionsInArray[a]):e.css2slide(e.positionsInArray[a],1),e.afterGo(),e.singleItemTransition(),!1;a=e.positionsInArray[a];!0===e.browser.support3d?(e.isCss3Finish=!1,!0===b?(e.swapSpeed("paginationSpeed"),f.setTimeout(function(){e.isCss3Finish=!0},e.options.paginationSpeed)):"rewind"===b?(e.swapSpeed(e.options.rewindSpeed),
f.setTimeout(function(){e.isCss3Finish=!0},e.options.rewindSpeed)):(e.swapSpeed("slideSpeed"),f.setTimeout(function(){e.isCss3Finish=!0},e.options.slideSpeed)),e.transition3d(a)):!0===b?e.css2slide(a,e.options.paginationSpeed):"rewind"===b?e.css2slide(a,e.options.rewindSpeed):e.css2slide(a,e.options.slideSpeed);e.afterGo()},jumpTo:function(a){"function"===typeof this.options.beforeMove&&this.options.beforeMove.apply(this,[this.$elem]);a>=this.maximumItem||-1===a?a=this.maximumItem:0>=a&&(a=0);this.swapSpeed(0);
!0===this.browser.support3d?this.transition3d(this.positionsInArray[a]):this.css2slide(this.positionsInArray[a],1);this.currentItem=this.owl.currentItem=a;this.afterGo()},afterGo:function(){this.prevArr.push(this.currentItem);this.prevItem=this.owl.prevItem=this.prevArr[this.prevArr.length-2];this.prevArr.shift(0);this.prevItem!==this.currentItem&&(this.checkPagination(),this.checkNavigation(),this.eachMoveUpdate(),!1!==this.options.autoPlay&&this.checkAp());"function"===typeof this.options.afterMove&&
this.prevItem!==this.currentItem&&this.options.afterMove.apply(this,[this.$elem])},stop:function(){this.apStatus="stop";f.clearInterval(this.autoPlayInterval)},checkAp:function(){"stop"!==this.apStatus&&this.play()},play:function(){var a=this;a.apStatus="play";if(!1===a.options.autoPlay)return!1;f.clearInterval(a.autoPlayInterval);a.autoPlayInterval=f.setInterval(function(){a.next(!0)},a.options.autoPlay)},swapSpeed:function(a){"slideSpeed"===a?this.$owlWrapper.css(this.addCssSpeed(this.options.slideSpeed)):
"paginationSpeed"===a?this.$owlWrapper.css(this.addCssSpeed(this.options.paginationSpeed)):"string"!==typeof a&&this.$owlWrapper.css(this.addCssSpeed(a))},addCssSpeed:function(a){return{"-webkit-transition":"all "+a+"ms ease","-moz-transition":"all "+a+"ms ease","-o-transition":"all "+a+"ms ease",transition:"all "+a+"ms ease"}},removeTransition:function(){return{"-webkit-transition":"","-moz-transition":"","-o-transition":"",transition:""}},doTranslate:function(a){"rtl"==this.options.direction&&(a=
-a);return{"-webkit-transform":"translate3d("+a+"px, 0px, 0px)","-moz-transform":"translate3d("+a+"px, 0px, 0px)","-o-transform":"translate3d("+a+"px, 0px, 0px)","-ms-transform":"translate3d("+a+"px, 0px, 0px)",transform:"translate3d("+a+"px, 0px,0px)"}},transition3d:function(a){this.$owlWrapper.css(this.doTranslate(a))},css2move:function(a){var b;"rtl"==this.options.direction?b={right:a}:b={left:a};this.$owlWrapper.css(b)},css2slide:function(a,b){var c=this,e;"rtl"==c.options.direction?e={right:a}:
e={left:a};c.isCssFinish=!1;c.$owlWrapper.stop(!0,!0).animate(e,{duration:b||c.options.slideSpeed,complete:function(){c.isCssFinish=!0}})},checkBrowser:function(){var a=h.createElement("div");a.style.cssText="  -moz-transform:translate3d(0px, 0px, 0px); -ms-transform:translate3d(0px, 0px, 0px); -o-transform:translate3d(0px, 0px, 0px); -webkit-transform:translate3d(0px, 0px, 0px); transform:translate3d(0px, 0px, 0px)";a=a.style.cssText.match(/translate3d\(0px, 0px, 0px\)/g);this.browser={support3d:null!==
a&&1===a.length,isTouch:"ontouchstart"in f||f.navigator.msMaxTouchPoints}},moveEvents:function(){if(!1!==this.options.mouseDrag||!1!==this.options.touchDrag)this.gestures(),this.disabledEvents()},eventTypes:function(){var a=["s","e","x"];this.ev_types={};!0===this.options.mouseDrag&&!0===this.options.touchDrag?a=["touchstart.owl mousedown.owl","touchmove.owl mousemove.owl","touchend.owl touchcancel.owl mouseup.owl"]:!1===this.options.mouseDrag&&!0===this.options.touchDrag?a=["touchstart.owl","touchmove.owl",
"touchend.owl touchcancel.owl"]:!0===this.options.mouseDrag&&!1===this.options.touchDrag&&(a=["mousedown.owl","mousemove.owl","mouseup.owl"]);this.ev_types.start=a[0];this.ev_types.move=a[1];this.ev_types.end=a[2]},disabledEvents:function(){this.$elem.on("dragstart.owl",function(a){a.preventDefault()});this.$elem.on("mousedown.disableTextSelect",function(a){return c(a.target).is("input, textarea, select, option")})},gestures:function(){function a(a){if(void 0!==a.touches)return{x:a.touches[0].pageX,
y:a.touches[0].pageY};if(void 0===a.touches){if(void 0!==a.pageX)return{x:a.pageX,y:a.pageY};if(void 0===a.pageX)return{x:a.clientX,y:a.clientY}}}function b(a){"on"===a?(c(h).on(d.ev_types.move,g),c(h).on(d.ev_types.end,e)):"off"===a&&(c(h).off(d.ev_types.move),c(h).off(d.ev_types.end))}function g(b){b=b.originalEvent||b||f.event;"rtl"==d.options.direction?(d.newPosX=-a(b).x-k.offsetX,d.newPosY=a(b).y-k.offsetY,d.newRelativeX=d.newPosX+k.relativePos):(d.newPosX=a(b).x-k.offsetX,d.newPosY=a(b).y-k.offsetY,
d.newRelativeX=d.newPosX-k.relativePos);"function"===typeof d.options.startDragging&&!0!==k.dragging&&0!==d.newRelativeX&&(k.dragging=!0,d.options.startDragging.apply(d,[d.$elem]));(8<d.newRelativeX||-8>d.newRelativeX)&&!0===d.browser.isTouch&&(void 0!==b.preventDefault?b.preventDefault():b.returnValue=!1,k.sliding=!0);(10<d.newPosY||-10>d.newPosY)&&!1===k.sliding&&c(h).off("touchmove.owl");d.newPosX=Math.max(Math.min(d.newPosX,d.newRelativeX/5),d.maximumPixels+d.newRelativeX/5);!0===d.browser.support3d?
d.transition3d(d.newPosX):d.css2move(d.newPosX)}function e(a){a=a.originalEvent||a||f.event;a.target=a.target||a.srcElement;k.dragging=!1;!0!==d.browser.isTouch&&d.$owlWrapper.removeClass("grabbing");d.dragDirection="rtl"==d.options.direction?0>d.newRelativeX?d.owl.dragDirection="right":d.owl.dragDirection="left":0>d.newRelativeX?d.owl.dragDirection="left":d.owl.dragDirection="right";if(0!==d.newRelativeX){var e=d.getNewPosition();d.goTo(e,!1,"drag");k.targetElement===a.target&&!0!==d.browser.isTouch&&
(c(a.target).on("click.disable",function(a){a.stopImmediatePropagation();a.stopPropagation();a.preventDefault();c(a.target).off("click.disable")}),a=c._data(a.target,"events").click,e=a.pop(),a.splice(0,0,e))}b("off")}var d=this,k={offsetX:0,offsetY:0,baseElWidth:0,relativePos:0,position:null,minSwipe:null,maxSwipe:null,sliding:null,dargging:null,targetElement:null};d.isCssFinish=!0;d.$elem.on(d.ev_types.start,".owl-wrapper",function(e){e=e.originalEvent||e||f.event;if(3===e.which)return!1;if(!(d.itemsAmount<=
d.options.items)){if(!1===d.isCssFinish&&!d.options.dragBeforeAnimFinish||!1===d.isCss3Finish&&!d.options.dragBeforeAnimFinish)return!1;!1!==d.options.autoPlay&&f.clearInterval(d.autoPlayInterval);!0===d.browser.isTouch||d.$owlWrapper.hasClass("grabbing")||d.$owlWrapper.addClass("grabbing");d.newPosX=0;d.newRelativeX=0;c(this).css(d.removeTransition());var g=c(this).position();"rtl"==d.options.direction?(positionRight=d.$owlItems.eq(0).width()*d.currentItem,k.relativePos=positionRight,k.offsetX=-a(e).x+
positionRight):(k.relativePos=g.left,k.offsetX=a(e).x-g.left);k.offsetY=a(e).y-g.top;b("on");k.sliding=!1;k.targetElement=e.target||e.srcElement}})},getNewPosition:function(){var a=this.closestItem();a>this.maximumItem?a=this.currentItem=this.maximumItem:0<=this.newPosX&&(this.currentItem=a=0);return a},closestItem:function(){var a=this,b=!0===a.options.scrollPerPage?a.pagesInArray:a.positionsInArray,g=a.newPosX,e=null;c.each(b,function(d,f){g-a.itemWidth/20>b[d+1]&&g-a.itemWidth/20<f&&"left"===a.moveDirection()?
(e=f,a.currentItem=!0===a.options.scrollPerPage?c.inArray(e,a.positionsInArray):d):g+a.itemWidth/20<f&&g+a.itemWidth/20>(b[d+1]||b[d]-a.itemWidth)&&"right"===a.moveDirection()&&(!0===a.options.scrollPerPage?(e=b[d+1]||b[b.length-1],a.currentItem=c.inArray(e,a.positionsInArray)):(e=b[d+1],a.currentItem=d+1))});return a.currentItem},moveDirection:function(){if(0>this.newRelativeX){var a="right";this.playDirection="next"}else a="left",this.playDirection="prev";return a},customEvents:function(){var a=
this;a.$elem.on("owl.next",function(){a.next()});a.$elem.on("owl.prev",function(){a.prev()});a.$elem.on("owl.play",function(b,c){a.options.autoPlay=c;a.play();a.hoverStatus="play"});a.$elem.on("owl.stop",function(){a.stop();a.hoverStatus="stop"});a.$elem.on("owl.goTo",function(b,c){a.goTo(c)});a.$elem.on("owl.jumpTo",function(b,c){a.jumpTo(c)})},stopOnHover:function(){var a=this;!0===a.options.stopOnHover&&!0!==a.browser.isTouch&&!1!==a.options.autoPlay&&(a.$elem.on("mouseover",function(){a.stop()}),
a.$elem.on("mouseout",function(){"stop"!==a.hoverStatus&&a.play()}))},lazyLoad:function(){var a,b;if(!1===this.options.lazyLoad)return!1;for(a=0;a<this.itemsAmount;a+=1){var g=c(this.$owlItems[a]);if("loaded"!==g.data("owl-loaded")){var e=g.data("owl-item");var d=g.find(".lazyOwl");"string"!==typeof d.data("src")?g.data("owl-loaded","loaded"):(void 0===g.data("owl-loaded")&&(d.hide(),g.addClass("loading").data("owl-loaded","checked")),(b=!0===this.options.lazyFollow?e>=this.currentItem:!0)&&e<this.currentItem+
this.options.items&&d.length&&this.lazyPreload(g,d))}}},lazyPreload:function(a,b){function c(){a.data("owl-loaded","loaded").removeClass("loading");b.removeAttr("data-src");"fade"===d.options.lazyEffect?b.fadeIn(400):b.show();"function"===typeof d.options.afterLazyLoad&&d.options.afterLazyLoad.apply(this,[d.$elem])}function e(){k+=1;d.completeImg(b.get(0))||!0===h?c():100>=k?f.setTimeout(e,100):c()}var d=this,k=0;if("DIV"===b.prop("tagName")){b.css("background-image","url("+b.data("src")+")");var h=
!0}else b[0].src=b.data("src");e()},autoHeight:function(){function a(){var a=c(g.$owlItems[g.currentItem]).height();g.wrapperOuter.css("height",a+"px");g.wrapperOuter.hasClass("autoHeight")||f.setTimeout(function(){g.wrapperOuter.addClass("autoHeight")},0)}function b(){d+=1;g.completeImg(e.get(0))?a():100>=d?f.setTimeout(b,100):g.wrapperOuter.css("height","")}var g=this,e=c(g.$owlItems[g.currentItem]).find("img");if(void 0!==e.get(0)){var d=0;b()}else a()},completeImg:function(a){return!a.complete||
"undefined"!==typeof a.naturalWidth&&0===a.naturalWidth?!1:!0},onVisibleItems:function(){var a;!0===this.options.addClassActive&&this.$owlItems.removeClass("active");this.visibleItems=[];for(a=this.currentItem;a<this.currentItem+this.options.items;a+=1)this.visibleItems.push(a),!0===this.options.addClassActive&&c(this.$owlItems[a]).addClass("active");this.owl.visibleItems=this.visibleItems},transitionTypes:function(a){this.outClass="owl-"+a+"-out";this.inClass="owl-"+a+"-in"},singleItemTransition:function(){var a=
this,b=a.outClass,c=a.inClass,e=a.$owlItems.eq(a.currentItem),d=a.$owlItems.eq(a.prevItem),f=Math.abs(a.positionsInArray[a.currentItem])+a.positionsInArray[a.prevItem],h=Math.abs(a.positionsInArray[a.currentItem])+a.itemWidth/2;a.isTransition=!0;a.$owlWrapper.addClass("owl-origin").css({"-webkit-transform-origin":h+"px","-moz-perspective-origin":h+"px","perspective-origin":h+"px"});d.css({position:"relative",left:f+"px"}).addClass(b).on("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend",
function(){a.endPrev=!0;d.off("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend");a.clearTransStyle(d,b)});e.addClass(c).on("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend",function(){a.endCurrent=!0;e.off("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend");a.clearTransStyle(e,c)})},clearTransStyle:function(a,b){a.css({position:"",left:""}).removeClass(b);this.endPrev&&this.endCurrent&&(this.$owlWrapper.removeClass("owl-origin"),this.isTransition=this.endCurrent=
this.endPrev=!1)},owlStatus:function(){this.owl={userOptions:this.userOptions,baseElement:this.$elem,userItems:this.$userItems,owlItems:this.$owlItems,currentItem:this.currentItem,prevItem:this.prevItem,visibleItems:this.visibleItems,isTouch:this.browser.isTouch,browser:this.browser,dragDirection:this.dragDirection}},clearEvents:function(){this.$elem.off(".owl owl mousedown.disableTextSelect");c(h).off(".owl owl");c(f).off("resize",this.resizer)},unWrap:function(){0!==this.$elem.children().length&&
(this.$owlWrapper.unwrap(),this.$userItems.unwrap().unwrap(),this.owlControls&&this.owlControls.remove());this.clearEvents();this.$elem.attr("style",this.$elem.data("owl-originalStyles")||"").attr("class",this.$elem.data("owl-originalClasses"))},destroy:function(){this.stop();f.clearInterval(this.checkVisible);this.unWrap();this.$elem.removeData()},reinit:function(a){a=c.extend({},this.userOptions,a);this.unWrap();this.init(a,this.$elem)},addItem:function(a,b){if(!a)return!1;if(0===this.$elem.children().length)return this.$elem.append(a),
this.setVars(),!1;this.unWrap();b=void 0===b||-1===b?-1:b;b>=this.$userItems.length||-1===b?this.$userItems.eq(-1).after(a):this.$userItems.eq(b).before(a);this.setVars()},removeItem:function(a){if(0===this.$elem.children().length)return!1;a=void 0===a||-1===a?-1:a;this.unWrap();this.$userItems.eq(a).remove();this.setVars()}};c.fn.owlCarousel=function(a){return this.each(function(){if(!0===c(this).data("owl-init"))return!1;c(this).data("owl-init",!0);var b=Object.create(l);b.init(a,this);c.data(this,
"owlCarousel",b)})};c.fn.owlCarousel.options={direction:"ltr",items:5,itemsCustom:!1,itemsDesktop:[1199,4],itemsDesktopSmall:[979,3],itemsTablet:[768,2],itemsTabletSmall:!1,itemsMobile:[479,1],singleItem:!1,itemsScaleUp:!1,slideSpeed:200,paginationSpeed:800,rewindSpeed:1E3,autoPlay:!1,stopOnHover:!1,navigation:!1,navigationText:["prev","next"],rewindNav:!0,scrollPerPage:!1,pagination:!0,paginationNumbers:!1,responsive:!0,responsiveRefreshRate:200,responsiveBaseWidth:f,baseClass:"owl-carousel",theme:"owl-theme",
lazyLoad:!1,lazyFollow:!0,lazyEffect:"fade",autoHeight:!1,jsonPath:!1,jsonSuccess:!1,dragBeforeAnimFinish:!0,mouseDrag:!0,touchDrag:!0,addClassActive:!1,transitionStyle:!1,beforeUpdate:!1,afterUpdate:!1,beforeInit:!1,afterInit:!1,beforeMove:!1,afterMove:!1,afterAction:!1,startDragging:!1,afterLazyLoad:!1}})(jQuery,window,document);
