/*
 * XenForo media_comments.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,f){a instanceof String&&(a=String(a));for(var g=a.length,b=0;b<g;b++){var c=a[b];if(d.call(f,c,b,a))return{i:b,v:c}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,f){a!=Array.prototype&&a!=Object.prototype&&(a[d]=f.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,d,f,g){if(d){f=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var b=a[g];b in f||(f[b]={});f=f[b]}a=a[a.length-1];g=f[a];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6","es3");
!function(a,d,f,g){XenForo.XenGalleryMedia={Comment:function(b){b.bind("AutoValidationComplete",function(c){c.ajaxData.templateHtml&&(c.preventDefault(),a("#MediaNoComments").slideUp(XenForo.speed.fast,function(){new XenForo.ExtLoader(c.ajaxData,function(){a(c.ajaxData.templateHtml).xfInsert("appendTo","#MediaNewComments")});a(".MediaComment").find("textarea").val("");var e=a("#CommentForm").find("textarea");e.val("");(e=e.data("XenForo.BbCodeWysiwygEditor"))&&e.resetEditor();b.find("input[name=date]").val(c.ajaxData.date);
b.find("input:submit").removeAttr("disabled").removeClass("disabled")}))})},InlineComment:function(b){b.bind("AutoValidationComplete",function(c){var e=b.closest("div.xenOverlay").data("overlay");e&&e.getTrigger().data("target");c.ajaxData.templateHtml&&(c.preventDefault(),e&&e.close().getTrigger().data("XenForo.OverlayTrigger").deCache(),new XenForo.ExtLoader(c.ajaxData,function(){var b=c.ajaxData.commentId;b&&a(c.ajaxData.templateHtml).xfInsert("replaceAll","#comment-"+b,"xfShow")}),a(".MediaComment").find("textarea").val(""),
b.find("input[name=date]").val(c.ajaxData.date),b.find("input:submit").removeAttr("disabled").removeClass("disabled"))})},ShowComment:function(b){b.click(function(c){c.preventDefault();var e=b.data("commentid");e&&XenForo.ajax(b.attr("href"),{},function(b,c){a("#comment-"+e).xfFadeUp();a(b.templateHtml).xfInsert("insertAfter","#comment-"+e).xfFadeDown()})})},CreateReply:function(b){b.click(function(c){c.preventDefault();var e=b.data("username");c=a("#CommentForm");if(e){var d=XenForo.getEditorInForm(c);
e="@"+e+" ";if(!d)return!1;a(f).scrollTop(c.offset().top);d.$editor?(d.focus(!0),d.insertHtml(XenForo.htmlspecialchars(e)),d.$editor.data("xenForoElastic")&&d.$editor.data("xenForoElastic")()):(d.focus(),d.val(d.val()+e))}})}};XenForo.register("form.MediaComment","XenForo.XenGalleryMedia.Comment");XenForo.register("form.MediaInlineComment","XenForo.XenGalleryMedia.InlineComment");XenForo.register("a.MediaShowComment","XenForo.XenGalleryMedia.ShowComment");XenForo.register("a.ReplyLink","XenForo.XenGalleryMedia.CreateReply")}(jQuery,
this,document);
