/*
 * XenForo media_embed.min.js
 * Copyright 2010-2019 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,c){a instanceof String&&(a=String(a));for(var e=a.length,b=0;b<e;b++){var f=a[b];if(d.call(c,f,b,a))return{i:b,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,d,c,e){if(d){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var b=a[e];b in c||(c[b]={});c=c[b]}a=a[a.length-1];e=c[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
!function(a,d,c,e){XenForo.XenGalleryMediaVideo=function(a){this.__construct(a)};XenForo.XenGalleryMediaVideo.prototype={__construct:function(b){this.$input=b;(this.media_id=b.data("mediaid"))&&a("#VideoPreviewArea").show();if(this.url="index.php?xengallery/preview-video&_xfResponseType=json&media_id="+this.media_id)this.$addButton=a("#AddButton"),this.$addButton.bind({click:a.context(this,"getVideoPreview")}),this.$updateButton=a("#UpdateButton"),this.$updateButton.bind({click:a.context(this,"replaceVideoPreview")}),
a("#VideoPreviewArea").on("click",".DeleteVideo",function(b){b.preventDefault();b=a(b.currentTarget).data("target");a(b).remove();a(".videoEmbed").length||(a("#VideoPreviewArea").xfFadeUp(XenForo.speed.fast),a(".VideoPreviewSubmitUnit").hide());return!1})},getVideoPreview:function(){this.xhr=XenForo.ajax(this.url,{embed_url:this.$input.val(),container_type:a('input[name="container_type"]').val(),container_id:a('input[name="container_id"]').val()},a.context(this,"ajaxSuccess"),{error:"failure"});this.$input.val("")},
replaceVideoPreview:function(){this.xhr=XenForo.ajax(this.url,{embed_url:this.$input.val(),container_type:a('input[name="container_type"]').val(),container_id:a('input[name="container_id"]').val()},a.context(this,"ajaxSuccess"),{error:!1});a(".thumbContainer").remove()},ajaxSuccess:function(b){b.templateHtml?(new XenForo.ExtLoader(b,function(){a("#VideoPreviewArea").xfFadeDown(XenForo.speed.fast);var c=a(b.templateHtml),d=c.find(".AttachmentText");c.xfInsert("prependTo",".VideoPreviewContainer .AttachmentList_video_embed",
"xfShow");d.find(".itemExtraInput.itemInputs").data("expanded")&&d.find("a.ToggleTrigger.ItemToggleTrigger").click()}),a(".VideoPreviewSubmitUnit").show()):(XenForo.alert(b.error),a(".videoEmbed").length||(a("#VideoPreviewArea").xfFadeUp(XenForo.speed.fast),a(".VideoPreviewSubmitUnit").hide()))}};XenForo.register("input.VideoLoader","XenForo.XenGalleryMediaVideo")}(jQuery,this,document);
